<?php 
function decimalHours($time)
{
    $hms = explode(":", $time);
    return ($hms[0] + ($hms[1]/60) + ($hms[2]/3600));
}
function build_calendar_Holiday_View(){
	$calendar = "<tr class=xl727473 height=19 style='mso-height-source:userset;height:14.25pt'>
  <td colspan=2 height=19 class=xl2607473 style='height:14.25pt'>Total LOE<span
  style='mso-spacerun:yes'>  </span>%age</td>
 ";
 $var=1;
 while ($var <= 38) {
 	$calendar .= "<td class=xl727473></td>";
 	$var++;
 }
 $calendar .= "</tr>";
	return $calendar;
}
function build_calendar($month,$year,$dateArray,$TMSCData,$sentTimesSheets,$leaveTypes,$empHolidays) {
	$lastDateOfMonth = date("Y-m-t", strtotime($TMSCData[0]['form']));
	$lastDateOfMonthTo = date("Y-m-t", strtotime($TMSCData[0]['to']));
	$date_diff = date_diff(date_create($TMSCData[0]['form']),date_create($lastDateOfMonth));
	$date_diffTo = date_diff(date_create($lastDateOfMonthTo),date_create($TMSCData[0]['to']));
	$date_diffTotal = date_diff(date_create($TMSCData[0]['form']),date_create($TMSCData[0]['to']));
	$Total = (strtotime($TMSCData[0]['form']) - strtotime($TMSCData[0]['to']))/60/60/24 * (-1);
	$DateFrom = (int)$date_diff->format('%d')+1;
	$DateTo = (int)$date_diffTo->format('%d')+1;
	$Total = $Total - $DateFrom;

	// var_dump($Total);
	// var_dump($DateFrom);
	// var_dump($DateTo);
	// var_dump($lastDateOfMonth);
	// var_dump($lastDateOfMonthTo);
	// var_dump($leaveTypes);
	// for ($x = 0; $x < count($leaveTypes); $x++) {
	// 	var_dump($leaveTypes[$x]['leavetype']);
	// }
	// die();
     // Create array containing abbreviations of days of week.
     $daysOfWeek = array('S','M','T','W','T','F','S','S','M','T','W','T','F','S','S','M','T','W','T','F','S','S','M','T','W','T','F','S','S','M','T','W','T','F','S');

     // What is the first day of the month in question?
     $firstDayOfMonth = mktime(0,0,0,$month,1,$year);

     // How many days does this month contain?
     $numberDays = date('t',$firstDayOfMonth);

     // Retrieve some information about the first day of the
     // month in question.
     $dateComponents = getdate($firstDayOfMonth);

     // What is the name of the month in question?
     $monthName = $dateComponents['month'];
     $monthNameL = date("F", strtotime($TMSCData[0]['form']));
     $yearNameL = date("Y", strtotime($TMSCData[0]['form']));

     // What is the index value (0-6) of the first day of the
     // month in question.
     $dayOfWeek = $dateComponents['wday'];

     // Create the table tag opener and day headers

     // $calendar = "<table class='calendar'>";
     // $calendar .= "<caption>$monthNameL $yearNameL Actual Time ";
     $calendar .= "<tr class=xl867473 height=35 style='mso-height-source:userset;height:26.25pt'>
  <td colspan=3 rowspan=2 height=61 class=xl2737473 style='border-bottom:1.0pt solid black;
  height:45.75pt'>Description</td>
  <td colspan=".(int)$DateFrom." class=xl2797473 width=222 style='border-right:1.0pt solid black;
  width:168pt'>$monthNameL $yearNameL Actual Time</td>
  <td colspan=".$Total." class=xl2827473 style='border-right:1.0pt solid black;
  border-left:none'>$monthName $year<span style='mso-spacerun:yes'>  </span>Actual
  Time</td>
  <td colspan=".$DateTo." class=xl2857473 style='border-right:1.0pt solid black;
  border-left:none'>$monthName $year <br>
    Estimated Time</td>
  <td rowspan=3 class=xl2707473 width=43 style='width:32pt'>Total Hours</td>
 </tr>";
     // $calendar .= "$monthName $year Actual Time ";
     // $calendar .= "$monthName $year Estimated Time</caption>";
     $calendar .= "<tr class=xl877473 height=26 style='mso-height-source:userset;height:19.5pt'>";

     // Create the calendar headers

     // foreach($daysOfWeek as $day) {
     //      $calendar .= "<th class='header'>$day</th>";
     // } 

     // Create the rest of the calendar

     // Initiate the day counter, starting with the 1st.

     $currentDay = 1;

     // $calendar .= "</tr><tr>";

     // The variable $dayOfWeek is used to
     // ensure that the calendar
     // display consists of exactly 7 columns.

     // if ($dayOfWeek > 0) { 
     //      $calendar .= "<td colspan='$dayOfWeek'>&nbsp;</td>"; 
     // }
     
     $month = str_pad($month, 2, "0", STR_PAD_LEFT);

     $currentDayL = date("d", strtotime($TMSCData[0]['form']));
     $numberDaysL = date("t", strtotime($TMSCData[0]['form']));
     $dayOfWeekL = 0;
     $monthL = date("m", strtotime($TMSCData[0]['form']));
     $yearL = date("Y", strtotime($TMSCData[0]['form']));
     $project = '';
     $task = '';
     foreach ($sentTimesSheets as $key => $value) {
     	$project = $value['project_name']!=null?$value['project_name']:$project;
     	$task = $value['task']!=null?$value['task']:$task;
     }
     // var_dump($sentTimesSheets);
     $calendarP = "";
     $calendarL = "<td height=31 class=xl1357473 style='height:23.25pt'>$project</td>
  <td class=xl1057473 style='border-left:none' colspan=2>$task</td>";
  	$calendarS = "";

  	$calendarSpace .= "<tr height=31 style='mso-height-source:userset;height:23.25pt'><td height=31 class=xl1457473 style='height:23.25pt;border-top:none'>&nbsp;</td>
  <td class=xl1057473 style='border-left:none'><span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl1037473 style='border-top:none;border-left:none'>&nbsp;</td>";

  $calendarLeaveHeader .= "<tr height=31 style='mso-height-source:userset;height:23.25pt'><td height=31 class=xl1097473 style='height:23.25pt;border-top:none'>LEAVE</td>
  <td class=xl1057473 style='border-left:none'><span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl1037473 style='border-top:none;border-left:none'>&nbsp;</td>";

  $calendarSickleave .= "<td height=33 class=xl687473 style='height:24.75pt'>Sick leave</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>";

  $calendarMaternityLeave .= "<td height=33 class=xl687473 style='height:24.75pt'>Maternity leave</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>";

  $calendarPaternityLeave .= "<td height=33 class=xl687473 style='height:24.75pt'>Paternity Leave</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>";

  $calendarFamilyLeave .= "<td height=33 class=xl687473 style='height:24.75pt'>Family Leave</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>";

  $calendarPublicHoliday .= "<td height=33 class=xl687473 style='height:24.75pt'>Public Holiday</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>";

  $calendarStudyleave .= "<td height=33 class=xl687473 style='height:24.75pt'>Study leave</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>";

  $calendarAnnualLeave .= "<td height=33 class=xl687473 style='height:24.75pt'>Annual Leave</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>";

  $calendarFloatingHoliday .= "<td height=33 class=xl687473 style='height:24.75pt'>Floating Holiday</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>";

  $calendarOther .= "<td height=33 class=xl687473 style='height:24.75pt'>Other</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>";

  $calendarSubTotalLeave = "<td height=29 class=xl1177473 style='height:21.75pt'>Sub Total <br>
    Leaves</td>
  <td class=xl1087473 style='border-left:none'>&nbsp;</td>
  <td class=xl1087473 style='border-left:none'>&nbsp;</td>";

  $caledarGrandTotal = "<tr height=29 style='mso-height-source:userset;height:21.75pt'>
  <td height=29 class=xl1187473 style='height:21.75pt;border-top:none'>Grand
  Total</td>
  <td class=xl1197473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1197473 style='border-top:none;border-left:none'>&nbsp;</td>";
     // $calendarL = "<tr>";
     // var_dump(date("F", strtotime($TMSCData[0]['form'])));
  $holiday_names = explode(',', $empHolidays['holiday_names']);
  $holiday_dates = explode(',', $empHolidays['holiday_dates']);
  // var_dump($holiday_dates);
  // die();
  	 $totalTime = 0;
     while ($currentDayL <= $numberDaysL) {

          // Seventh column (Saturday) reached. Start a new row.

          // if ($dayOfWeek == 30) {

          //      $dayOfWeek = 0;
          //      $calendar .= "</tr><tr>";

          // }
          
          $currentDayRel = str_pad($currentDayL, 2, "0", STR_PAD_LEFT);
          
          $date = "$yearL-$monthL-$currentDayRel";
          $get_name = date('l', strtotime($date)); //get week day
          $day_name = substr($get_name, 0, 3); // Trim day name to 3 chars

          $holiday_signal = false;
          foreach ($holiday_dates as $key => $value) {
          	if($value==$date){
          		$holiday_signal=true;
          	}
          }

          if($day_name=='Sun' || $day_name=='Sat')
          	$calendar .= "<td class=xl987473 style='border-top:none'>$currentDayL</td>";
          else if($holiday_signal)
          	$calendar .= "<td class=xl987473 style='border-top:none'>$currentDayL</td>";
          else
          	$calendar .= "<td class=xl1127473 style='border-top:none'>$currentDayL</td>";
          $time = '';
          $time = '';
          $dump = '';
          foreach ($sentTimesSheets as $key => $value) {
          	if($value[$date]!=null)
          	{
          		$time=$value[$date];
          		break;
          	}else{
          		$time = '00:00';
          	}
          }
          $totalTime += decimalHours($time);
          // var_dump($time);
          // var_dump($sentTimesSheets);
          // var_dump($date);
          // die();

          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarL .= "<td class=xl987473 style='border-top:none'>".$time."</td>";
          else if($holiday_signal)
          	$calendarL .= "<td class=xl987473 style='border-top:none'>".$time."</td>";
          else
          	$calendarL .= "<td class=xl1127473 style='border-top:none'>".$time."</td>";

          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarS .= "<td class=xl987473 style='border-top:none'>".$time."</td>";
          else if($holiday_signal)
          	$calendarS .= "<td class=xl987473 style='border-top:none'>".$time."</td>";
          else
          	$calendarS .= "<td class=xl1127473 style='border-top:none'>".$time."</td>";

          //official spacing
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarSpace .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarSpace .= "<td class=xl1127473 style='border-top:none'>&nbsp;</td>";

          	$calendarP .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";

          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==1&&$value['leavestatus']=='Approved')
          	{
          		$SickLeavetime="08:30";
          		break;
          	}else{
          		$SickLeavetime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==10&&$value['leavestatus']=='Approved')
          	{
          		$MaternityLeavetime="08:30";
          		break;
          	}else{
          		$MaternityLeavetime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==13&&$value['leavestatus']=='Approved')
          	{
          		$PaternityLeavetime="08:30";
          		break;
          	}else{
          		$PaternityLeavetime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==12&&$value['leavestatus']=='Approved')
          	{
          		$FamilyLeavetime="08:30";
          		break;
          	}else{
          		$FamilyLeavetime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==5&&$value['leavestatus']=='Approved')
          	{
          		$PublicHolidaytime="08:30";
          		break;
          	}else{
          		$PublicHolidaytime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==6&&$value['leavestatus']=='Approved')
          	{
          		$Studyleavetime="08:30";
          		break;
          	}else{
          		$Studyleavetime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==7&&$value['leavestatus']=='Approved')
          	{
          		$AnnualLeavetime="08:30";
          		break;
          	}else{
          		$AnnualLeavetime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==8&&$value['leavestatus']=='Approved')
          	{
          		$FloatingHolidaytime="08:30";
          		break;
          	}else{
          		$FloatingHolidaytime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==9&&$value['leavestatus']=='Approved')
          	{
          		$Othertime="08:30";
          		break;
          	}else{
          		$Othertime = '';
          	}
          }
          //official leave header
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarLeaveHeader .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarLeaveHeader .= "<td class=xl1127473 style='border-top:none'>&nbsp;</td>";

          //offical leave
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarSickleave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarSickleave .= "<td class=xl1127473 style='border-top:none'>$SickLeavetime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarMaternityLeave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarMaternityLeave .= "<td class=xl1127473 style='border-top:none'>$MaternityLeavetime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarPaternityLeave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarPaternityLeave .= "<td class=xl1127473 style='border-top:none'>$PaternityLeavetime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarFamilyLeave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarFamilyLeave .= "<td class=xl1127473 style='border-top:none'>$FamilyLeavetime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarPublicHoliday .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarPublicHoliday .= "<td class=xl1127473 style='border-top:none'>$PublicHolidaytime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarStudyleave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarStudyleave .= "<td class=xl1127473 style='border-top:none'>$Studyleavetime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarAnnualLeave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarAnnualLeave .= "<td class=xl1127473 style='border-top:none'>$AnnualLeavetime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarFloatingHoliday .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarFloatingHoliday .= "<td class=xl1127473 style='border-top:none'>$FloatingHolidaytime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarOther .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarOther .= "<td class=xl1127473 style='border-top:none'>$Othertime</td>";

          $calendarSubTotalLeave .= "<td class=xl1877473 width=37 style='width:28pt'>0</td>";
          $caledarGrandTotal .= "<td class=xl1877473 width=37 style='width:28pt'>0</td>";
          
          // $calendarL .= "<td class='day $day_name' rel='$date'>$currentDayL</td>";

          // Increment counters
 
          $currentDayL++;
          $dayOfWeekL++;

     }


     while ($currentDay <= $numberDays) {

          // Seventh column (Saturday) reached. Start a new row.

          // if ($dayOfWeek == 30) {

          //      $dayOfWeek = 0;
          //      $calendar .= "</tr><tr>";

          // }
          
          $currentDayRel = str_pad($currentDay, 2, "0", STR_PAD_LEFT);
          
          $date = "$year-$month-$currentDayRel";
          $get_name = date('l', strtotime($date)); //get week day
          $day_name = substr($get_name, 0, 3); // Trim day name to 3 chars

          $holiday_signal = false;
          foreach ($holiday_dates as $key => $value) {
          	if($value==$date){
          		$holiday_signal=true;
          	}
          }

          if($day_name=='Sun' || $day_name=='Sat')
          	$calendar .= "<td class=xl987473 style='border-top:none'>$currentDay</td>";
          else if($holiday_signal)
          	$calendar .= "<td class=xl987473 style='border-top:none'>$currentDay</td>";
          else
          	$calendar .= "<td class=xl1127473 style='border-top:none'>$currentDay</td>";

          $time = '';
          foreach ($sentTimesSheets as $key => $value) {
          	if($value[$date]!=null)
          	{
          		$time=$value[$date];
          		break;
          	}else{
          		$time = '00:00';
          	}
          }
          $totalTime += decimalHours($time);
          // var_dump($time);
          // var_dump($sentTimesSheets);
          // var_dump($date);
          // die();

          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarL .= "<td class=xl987473 style='border-top:none'>".$time."</td>";
          else if($holiday_signal)
          	$calendarL .= "<td class=xl987473 style='border-top:none'>".$time."</td>";
          else
          	$calendarL .= "<td class=xl1127473 style='border-top:none'>".$time."</td>";

          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarS .= "<td class=xl987473 style='border-top:none'>".$time."</td>";
          else if($holiday_signal)
          	$calendarS .= "<td class=xl987473 style='border-top:none'>".$time."</td>";
          else
          	$calendarS .= "<td class=xl1127473 style='border-top:none'>".$time."</td>";

          //official spacing
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarSpace .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else if($holiday_signal)
          	$calendarSpace .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarSpace .= "<td class=xl1127473 style='border-top:none'>&nbsp;</td>";

          $calendarP .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";

          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==1&&$value['leavestatus']=='Approved')
          	{
          		$SickLeavetime="08:30";
          		break;
          	}else{
          		$SickLeavetime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==10&&$value['leavestatus']=='Approved')
          	{
          		$MaternityLeavetime="08:30";
          		break;
          	}else{
          		$MaternityLeavetime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==13&&$value['leavestatus']=='Approved')
          	{
          		$PaternityLeavetime="08:30";
          		break;
          	}else{
          		$PaternityLeavetime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==12&&$value['leavestatus']=='Approved')
          	{
          		$FamilyLeavetime="08:30";
          		break;
          	}else{
          		$FamilyLeavetime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==5&&$value['leavestatus']=='Approved')
          	{
          		$PublicHolidaytime="08:30";
          		break;
          	}else{
          		$PublicHolidaytime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==6&&$value['leavestatus']=='Approved')
          	{
          		$Studyleavetime="08:30";
          		break;
          	}else{
          		$Studyleavetime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==15&&$value['leavestatus']=='Approved')
          	{
          		$AnnualLeavetime="08:30";
          		break;
          	}else{
          		$AnnualLeavetime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==8&&$value['leavestatus']=='Approved')
          	{
          		$FloatingHolidaytime="08:30";
          		break;
          	}else{
          		$FloatingHolidaytime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==9&&$value['leavestatus']=='Approved')
          	{
          		$Othertime="08:30";
          		break;
          	}else{
          		$Othertime = '';
          	}
          }
          //official leave header
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarLeaveHeader .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else if($holiday_signal)
          	$calendarLeaveHeader .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarLeaveHeader .= "<td class=xl1127473 style='border-top:none'>&nbsp;</td>";

          //offical leave
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarSickleave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else if($holiday_signal)
          	$calendarSickleave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarSickleave .= "<td class=xl1127473 style='border-top:none'>$SickLeavetime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarMaternityLeave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else if($holiday_signal)
          	$calendarMaternityLeave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarMaternityLeave .= "<td class=xl1127473 style='border-top:none'>$MaternityLeavetime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarPaternityLeave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else if($holiday_signal)
          	$calendarPaternityLeave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarPaternityLeave .= "<td class=xl1127473 style='border-top:none'>$PaternityLeavetime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarFamilyLeave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else if($holiday_signal)
          	$calendarFamilyLeave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarFamilyLeave .= "<td class=xl1127473 style='border-top:none'>$FamilyLeavetime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarPublicHoliday .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else if($holiday_signal)
          	$calendarPublicHoliday .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarPublicHoliday .= "<td class=xl1127473 style='border-top:none'>$PublicHolidaytime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarStudyleave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else if($holiday_signal)
          	$calendarStudyleave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarStudyleave .= "<td class=xl1127473 style='border-top:none'>$Studyleavetime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarAnnualLeave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else if($holiday_signal)
          	$calendarAnnualLeave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarAnnualLeave .= "<td class=xl1127473 style='border-top:none'>$AnnualLeavetime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarFloatingHoliday .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else if($holiday_signal)
          	$calendarFloatingHoliday .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarFloatingHoliday .= "<td class=xl1127473 style='border-top:none'>$FloatingHolidaytime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarOther .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else if($holiday_signal)
          	$calendarOther .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarOther .= "<td class=xl1127473 style='border-top:none'>$Othertime</td>";

          $calendarSubTotalLeave .= "<td class=xl1877473 width=37 style='width:28pt'>0</td>";
          $caledarGrandTotal .= "<td class=xl1877473 width=37 style='width:28pt'>0</td>";

          // $calendar .= "<td class=xl1127473 width=37 style='border-top:none;width:28pt'>$currentDay</td>";
          // $calendarL .= "<td class='day $day_name' rel='$date'>$currentDay</td>";
          if ($currentDay==$numberDays) {
          	$calendarL .= "<td class=xl1127473 style='border-top:none'>$totalTime</td>";
          	$calendarS .= "<td class=xl1127473 style='border-top:none'>$totalTime</td>";
          	$calendarSpace .= "<td class=xl1127473 style='border-top:none'>&nbsp;</td>";
          	$calendarSickleave .= "<td class=xl1127473 style='border-top:none'>&nbsp;</td>";
          	$calendarMaternityLeave .= "<td class=xl1127473 style='border-top:none'>&nbsp;</td>";
          	$calendarPaternityLeave .= "<td class=xl1127473 style='border-top:none'>&nbsp;</td>";
          	$calendarFamilyLeave .= "<td class=xl1127473 style='border-top:none'>&nbsp;</td>";
          	$calendarPublicHoliday .= "<td class=xl1127473 style='border-top:none'>&nbsp;</td>";
          	$calendarStudyleave .= "<td class=xl1127473 style='border-top:none'>&nbsp;</td>";
          	$calendarAnnualLeave .= "<td class=xl1127473 style='border-top:none'>&nbsp;</td>";
          	$calendarFloatingHoliday .= "<td class=xl1127473 style='border-top:none'>&nbsp;</td>";
          	$calendarOther .= "<td class=xl1127473 style='border-top:none'>&nbsp;</td>";
          	$calendarLeaveHeader .= "<td class=xl1127473 style='border-top:none'>&nbsp;</td>";
          	$calendarSubTotalLeave .= "<td class=xl1877473 width=37 style='width:28pt'>0</td>";
          	$caledarGrandTotal .= "<td class=xl1877473 width=37 style='width:28pt'>0</td>";
          }
          // Increment counters
 
          $currentDay++;
          $dayOfWeek++;

     }
     
     

     // Complete the row of the last week in month, if necessary

     // if ($dayOfWeek != 7) { 
     
     //      $remainingDays = 7 - $dayOfWeek;
     //      $calendar .= "<td colspan='$remainingDays'>&nbsp;</td>"; 

     // }
     
     $calendar .= "</tr>";
     // $calendarL .= "</tr>";

     // $calendar .= $calendarL;

     // $calendar .= "</table>";
     $calendar .= "<tr class=xl887473 height=26 style='mso-height-source:userset;height:19.5pt'>
  <td height=26 class=xl1307473 style='height:19.5pt;border-top:none'>Project</td>
  <td class=xl1317473 style='border-top:none;border-left:none'>Project Code</td>
  <td class=xl1327473 style='border-top:none;border-left:none'>Location</td>";
  	$calendar .= $calendarP;
  	$calendar .= "</tr>";

 $calendar .= "<tr class=xl897473 height=31 style='mso-height-source:userset;height:23.25pt'>";
 $calendar .= $calendarL."</tr>";
 $calendar .= $calendarSpace;
 $calendar .= $calendarSpace;
 $calendar .= $calendarSpace;
 $calendar .= $calendarSpace;

 $calendar .= "<tr height=34 style='mso-height-source:userset;height:25.5pt'>
  <td height=34 class=xl1077473 width=99 style='height:25.5pt;width:74pt'>Sub
  Total <br>
    Working days</td>
  <td class=xl1087473 style='border-left:none'><span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl1087473 style='border-left:none'>&nbsp;</td>";
  $calendar .= $calendarS."</tr>";
  $calendarSpace .= "</tr>";

  $calendar .= $calendarSpace;
  $calendar .= $calendarSpace;
  $calendar .= $calendarSpace;
  $calendar .= $calendarSpace;
  $calendar .= $calendarLeaveHeader;
  $calendar .= "</tr>";

  $calendar .= $calendarSickleave;
  $calendar .= "</tr>";
  $calendar .= $calendarMaternityLeave;
  $calendar .= "</tr>";
  $calendar .= $calendarPaternityLeave;
  $calendar .= "</tr>";
  $calendar .= $calendarFamilyLeave;
  $calendar .= "</tr>";
  $calendar .= $calendarPublicHoliday;
  $calendar .= "</tr>";
  $calendar .= $calendarStudyleave;
  $calendar .= "</tr>";
  $calendar .= $calendarAnnualLeave;
  $calendar .= "</tr>";
  $calendar .= $calendarFloatingHoliday;
  $calendar .= "</tr>";
  $calendar .= $calendarOther;
  $calendar .= "</tr>";
  $calendar .= $calendarSubTotalLeave;
  $calendar .= "</tr>";
  $calendar .= $caledarGrandTotal;
  $calendar .= "</tr>";


     return $calendar;

}

 ?>

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link rel=File-List
href="1.10.%202020%20Timesheet%20October%202020_files/filelist.xml">
<style id="1.10. 2020 Timesheet October 2020_7473_Styles">
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
-->
</style>
<link rel="stylesheet" type="text/css" href="<?php echo MEDIA_PATH; ?>css/timesheetreport.css">
</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="1.10. 2020 Timesheet October 2020_7473" align=center
x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=1724 class=xl727473
 style='border-collapse:collapse;table-layout:fixed;width:1300pt'>
 <col class=xl727473 width=99 style='mso-width-source:userset;mso-width-alt:
 3620;width:74pt'>
 <col class=xl897473 width=73 style='mso-width-source:userset;mso-width-alt:
 2669;width:55pt'>
 <col class=xl897473 width=66 style='mso-width-source:userset;mso-width-alt:
 2413;width:50pt'>
 <col class=xl727473 width=37 span=7 style='mso-width-source:userset;
 mso-width-alt:1353;width:28pt'>
 <col class=xl2597473 width=37 span=2 style='mso-width-source:userset;
 mso-width-alt:1353;width:28pt'>
 <col class=xl727473 width=37 span=5 style='mso-width-source:userset;
 mso-width-alt:1353;width:28pt'>
 <col class=xl2597473 width=37 style='mso-width-source:userset;mso-width-alt:
 1353;width:28pt'>
 <col class=xl727473 width=37 span=17 style='mso-width-source:userset;
 mso-width-alt:1353;width:28pt'>
 <col class=xl727473 width=39 span=5 style='mso-width-source:userset;
 mso-width-alt:1426;width:29pt'>
 <col class=xl727473 width=0 style='display:none;mso-width-source:userset;
 mso-width-alt:1133'>
 <col class=xl727473 width=0 style='display:none;mso-width-source:userset;
 mso-width-alt:1133'>
 <col class=xl727473 width=43 style='mso-width-source:userset;mso-width-alt:
 1572;width:32pt'>
 <col class=xl727473 width=0 style='display:none;mso-width-source:userset;
 mso-width-alt:1682'>
 <col class=xl727473 width=0 style='display:none;mso-width-source:userset;
 mso-width-alt:1682'>
 <col class=xl727473 width=0 style='display:none;mso-width-source:userset;
 mso-width-alt:2340'>
 <col class=xl727473 width=0 style='display:none;mso-width-source:userset;
 mso-width-alt:2340'>
 <col class=xl727473 width=0 style='display:none;mso-width-source:userset;
 mso-width-alt:2340'>
 <col class=xl727473 width=64 style='width:48pt'>
 <tr class=xl727473 height=37 style='mso-height-source:userset;height:27.75pt'>
  <td height=37 class=xl1207473 width=99 style='height:27.75pt;width:74pt'><a
  name="RANGE!A1:AR37">Name</a></td>
  <td colspan=9 class=xl2727473 width=398 style='width:301pt'><?php echo $this->fullName; ?></td>
  <td class=xl727473 width=37 style='width:28pt'></td>
  <td class=xl727473 width=37 style='width:28pt'></td>
  <td class=xl727473 width=37 style='width:28pt'></td>
  <td class=xl1217473 width=37 style='width:28pt'></td>
  <td class=xl727473 width=37 style='width:28pt'></td>
  <td class=xl727473 width=37 style='width:28pt'></td>
  <td class=xl727473 width=37 style='width:28pt'></td>
  <td class=xl727473 width=37 style='width:28pt'></td>
  <td class=xl727473 width=37 style='width:28pt'></td>
  <td class=xl727473 width=37 style='width:28pt'></td>
  <td class=xl727473 width=37 style='width:28pt'></td>
  <td class=xl727473 width=37 style='width:28pt'></td>
  <td class=xl727473 width=37 style='width:28pt'></td>
  <td class=xl727473 width=37 style='width:28pt'></td>
  <td class=xl727473 width=37 style='width:28pt'></td>
  <td class=xl1227473 width=37 style='width:28pt'></td>
  <td class=xl1227473 width=37 style='width:28pt'></td>
  <td class=xl1227473 width=37 style='width:28pt'></td>
  <td class=xl1227473 width=37 style='width:28pt'></td>
  <td class=xl1227473 width=37 style='width:28pt'></td>
  <td class=xl1227473 width=37 style='width:28pt'></td>
  <td class=xl1227473 width=37 style='width:28pt'></td>
  <td class=xl1227473 width=37 style='width:28pt'></td>
  <td class=xl1227473 width=37 style='width:28pt'></td>
  <td class=xl1227473 width=37 style='width:28pt'></td>
  <td class=xl1227473 width=39 style='width:29pt'></td>
  <td class=xl1227473 width=39 style='width:29pt'></td>
  <td class=xl1227473 width=39 style='width:29pt'></td>
  <td class=xl1227473 width=39 style='width:29pt'></td>
  <td class=xl1227473 width=39 style='width:29pt'></td>
  <td class=xl1227473 width=0></td>
  <td class=xl1227473 width=0></td>
  <td class=xl1227473 width=43 style='width:32pt'></td>
  <td class=xl727473 width=0></td>
  <td class=xl727473 width=0></td>
  <td class=xl727473 width=0></td>
  <td class=xl727473 width=0></td>
  <td class=xl727473 width=0></td>
  <td class=xl727473 width=64 style='width:48pt'></td>
 </tr>
 <tr class=xl727473 height=28 style='mso-height-source:userset;height:21.0pt'>
  <td height=28 class=xl1237473 style='height:21.0pt'></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1247473>&nbsp;</td>
  <td class=xl1247473>&nbsp;</td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
 </tr>
 <!-- <tr class=xl867473 height=35 style='mso-height-source:userset;height:26.25pt'>
  <td colspan=3 rowspan=2 height=61 class=xl2737473 style='border-bottom:1.0pt solid black;
  height:45.75pt'>Description</td>
  <td colspan=6 class=xl2797473 width=222 style='border-right:1.0pt solid black;
  width:168pt'>September 2020 Actual Time</td>
  <td colspan=23 class=xl2827473 style='border-right:1.0pt solid black;
  border-left:none'>October 2020<span style='mso-spacerun:yes'>  </span>Actual
  Time</td>
  <td colspan=8 class=xl2857473 style='border-right:1.0pt solid black;
  border-left:none'>October 2020 <br>
    Estimated Time</td>
  <td rowspan=3 class=xl2707473 width=43 style='width:32pt'>Total Hours</td>
 </tr> -->
 <!-- <tr class=xl877473 height=26 style='mso-height-source:userset;height:19.5pt'>
  <td height=26 class=xl2357473 style='height:19.5pt;border-top:none'>25</td>
  <td class=xl977473 style='border-top:none'>26</td>
  <td class=xl987473 style='border-top:none;border-left:none'>27</td>
  <td class=xl997473 style='border-top:none;border-left:none'>28</td>
  <td class=xl1907473 style='border-top:none'>29</td>
  <td class=xl997473 style='border-top:none;border-left:none'>30</td>
  <td class=xl1127473 width=37 style='border-top:none;width:28pt'>01</td>
  <td class=xl1127473 width=37 style='border-top:none;border-left:none;
  width:28pt'>02</td>
  <td class=xl987473 style='border-top:none;border-left:none'>03</td>
  <td class=xl977473 style='border-top:none'>04</td>
  <td class=xl1127473 width=37 style='border-top:none;border-left:none;
  width:28pt'>05</td>
  <td class=xl1127473 width=37 style='border-top:none;border-left:none;
  width:28pt'>06</td>
  <td class=xl1127473 width=37 style='border-top:none;border-left:none;
  width:28pt'>07</td>
  <td class=xl1137473 width=37 style='border-top:none;border-left:none;
  width:28pt'>08</td>
  <td class=xl1127473 width=37 style='border-top:none;width:28pt'>09</td>
  <td class=xl987473 style='border-top:none;border-left:none'>10</td>
  <td class=xl987473 style='border-top:none;border-left:none'>11</td>
  <td class=xl1987473 width=37 style='border-top:none;width:28pt'>12</td>
  <td class=xl1987473 width=37 style='border-top:none;width:28pt'>13</td>
  <td class=xl1127473 width=37 style='border-top:none;border-left:none;
  width:28pt'>14</td>
  <td class=xl1127473 width=37 style='border-top:none;border-left:none;
  width:28pt'>15</td>
  <td class=xl1127473 width=37 style='border-top:none;border-left:none;
  width:28pt'>16</td>
  <td class=xl987473 style='border-top:none;border-left:none'>17</td>
  <td class=xl977473 style='border-top:none'>18</td>
  <td class=xl1137473 width=37 style='border-top:none;border-left:none;
  width:28pt'>19</td>
  <td class=xl1127473 width=37 style='border-top:none;width:28pt'>20</td>
  <td class=xl1127473 width=37 style='border-top:none;border-left:none;
  width:28pt'>21</td>
  <td class=xl1127473 width=37 style='border-top:none;border-left:none;
  width:28pt'>22</td>
  <td class=xl1127473 width=37 style='border-top:none;border-left:none;
  width:28pt'>23</td>
  <td class=xl1267473>24</td>
  <td class=xl977473 style='border-top:none;border-left:none'>25</td>
  <td class=xl1127473 width=37 style='border-top:none;border-left:none;
  width:28pt'>26</td>
  <td class=xl997473 style='border-top:none;border-left:none'>27</td>
  <td class=xl997473 style='border-top:none'>28</td>
  <td class=xl1267473>29</td>
  <td class=xl997473 style='border-top:none'>30</td>
  <td class=xl1267473>31</td>
  <td class=xl877473></td>
  <td class=xl877473></td>
  <td class=xl877473></td>
  <td class=xl877473></td>
 </tr> -->
 <?php 
 	$dateComponents = getdate();

     $month = $dateComponents['mon'];                  
     $year = $dateComponents['year'];

     echo build_calendar($month,$year,$dateArray,$this->TMSCData,$this->sentTimesSheets,$this->leaveTypes,$this->empHolidaysWeekends);
  ?>
 <!-- <tr class=xl877473 height=0 style='display:none;mso-height-source:userset;
  mso-height-alt:465'>
  <td class=xl2367473 style='border-top:none'>Fri</td>
  <td class=xl947473 style='border-top:none;font-size:8.0pt;color:#9C0006;
  font-weight:400;text-decoration:none;text-underline-style:none;text-line-through:
  none;font-family:Calibri, sans-serif;border-top:.5pt solid windowtext;
  border-right:.5pt solid windowtext;border-bottom:.5pt solid windowtext;
  border-left:1.0pt solid windowtext;background:#FFC7CE;mso-pattern:black none'>Sat</td>
  <td class=xl957473 style='border-top:none;border-left:none;font-size:8.0pt;
  color:#9C0006;font-weight:400;text-decoration:none;text-underline-style:none;
  text-line-through:none;font-family:Calibri, sans-serif;border:.5pt solid windowtext;
  background:#FFC7CE;mso-pattern:black none'>Sun</td>
  <td class=xl967473 style='border-top:none;border-left:none'>Mon</td>
  <td class=xl1917473 style='border-top:none'>Tue</td>
  <td class=xl967473 style='border-top:none;border-left:none'>Wed</td>
  <td class=xl1147473 width=37 style='border-top:none;width:28pt'>Thu</td>
  <td class=xl2387473 style='border-top:none;border-left:none'>Fri</td>
  <td class=xl957473 style='border-top:none;border-left:none;font-size:8.0pt;
  color:#9C0006;font-weight:400;text-decoration:none;text-underline-style:none;
  text-line-through:none;font-family:Calibri, sans-serif;border:.5pt solid windowtext;
  background:#FFC7CE;mso-pattern:black none'>Sat</td>
  <td class=xl947473 style='border-top:none;font-size:8.0pt;color:#9C0006;
  font-weight:400;text-decoration:none;text-underline-style:none;text-line-through:
  none;font-family:Calibri, sans-serif;border-top:.5pt solid windowtext;
  border-right:.5pt solid windowtext;border-bottom:.5pt solid windowtext;
  border-left:1.0pt solid windowtext;background:#FFC7CE;mso-pattern:black none'>Sun</td>
  <td class=xl1157473 style='border-top:none;border-left:none'>Mon</td>
  <td class=xl1157473 style='border-top:none;border-left:none'>Tue</td>
  <td class=xl1157473 style='border-top:none;border-left:none'>Wed</td>
  <td class=xl1967473 style='border-top:none;border-left:none'>Thu</td>
  <td class=xl2387473 style='border-top:none'>Fri</td>
  <td class=xl957473 style='border-top:none;border-left:none;font-size:8.0pt;
  color:#9C0006;font-weight:400;text-decoration:none;text-underline-style:none;
  text-line-through:none;font-family:Calibri, sans-serif;border:.5pt solid windowtext;
  background:#FFC7CE;mso-pattern:black none'>Sat</td>
  <td class=xl957473 style='border-top:none;border-left:none;font-size:8.0pt;
  color:#9C0006;font-weight:400;text-decoration:none;text-underline-style:none;
  text-line-through:none;font-family:Calibri, sans-serif;border:.5pt solid windowtext;
  background:#FFC7CE;mso-pattern:black none'>Sun</td>
  <td class=xl1997473 style='border-top:none'>Mon</td>
  <td class=xl1997473 style='border-top:none'>Tue</td>
  <td class=xl1157473 style='border-top:none;border-left:none'>Wed</td>
  <td class=xl1157473 style='border-top:none;border-left:none'>Thu</td>
  <td class=xl2387473 style='border-top:none;border-left:none'>Fri</td>
  <td class=xl957473 style='border-top:none;border-left:none;font-size:8.0pt;
  color:#9C0006;font-weight:400;text-decoration:none;text-underline-style:none;
  text-line-through:none;font-family:Calibri, sans-serif;border:.5pt solid windowtext;
  background:#FFC7CE;mso-pattern:black none'>Sat</td>
  <td class=xl947473 style='border-top:none;font-size:8.0pt;color:#9C0006;
  font-weight:400;text-decoration:none;text-underline-style:none;text-line-through:
  none;font-family:Calibri, sans-serif;border-top:.5pt solid windowtext;
  border-right:.5pt solid windowtext;border-bottom:.5pt solid windowtext;
  border-left:1.0pt solid windowtext;background:#FFC7CE;mso-pattern:black none'>Sun</td>
  <td class=xl1967473 style='border-top:none;border-left:none'>Mon</td>
  <td class=xl1157473 style='border-top:none'>Tue</td>
  <td class=xl1157473 style='border-top:none;border-left:none'>Wed</td>
  <td class=xl1157473 style='border-top:none;border-left:none'>Thu</td>
  <td class=xl2387473 style='border-top:none;border-left:none'>Fri</td>
  <td class=xl1287473 style='border-top:none;font-size:8.0pt;color:#9C0006;
  font-weight:400;text-decoration:none;text-underline-style:none;text-line-through:
  none;font-family:Calibri, sans-serif;border-top:.5pt solid windowtext;
  border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;
  background:#FFC7CE;mso-pattern:black none'>Sat</td>
  <td class=xl947473 style='border-top:none;border-left:none;font-size:8.0pt;
  color:#9C0006;font-weight:400;text-decoration:none;text-underline-style:none;
  text-line-through:none;font-family:Calibri, sans-serif;border-top:.5pt solid windowtext;
  border-right:.5pt solid windowtext;border-bottom:.5pt solid windowtext;
  border-left:1.0pt solid windowtext;background:#FFC7CE;mso-pattern:black none'>Sun</td>
  <td class=xl1157473 style='border-top:none;border-left:none'>Mon</td>
  <td class=xl967473 style='border-top:none;border-left:none'>Tue</td>
  <td class=xl967473 style='border-top:none'>Wed</td>
  <td class=xl1287473 style='border-top:none'>Thu</td>
  <td class=xl967473 style='border-top:none'>Fri</td>
  <td class=xl1287473 style='border-top:none;font-size:8.0pt;color:#9C0006;
  font-weight:400;text-decoration:none;text-underline-style:none;text-line-through:
  none;font-family:Calibri, sans-serif;border-top:.5pt solid windowtext;
  border-right:1.0pt solid windowtext;border-bottom:none;border-left:none;
  background:#FFC7CE;mso-pattern:black none'>Sat</td>
  <td class=xl1297473 style='border-top:none'>&nbsp;</td>
  <td class=xl2097473 style='border-top:none'>Mon</td>
  <td class=xl877473></td>
  <td class=xl877473></td>
  <td class=xl877473></td>
  <td class=xl877473></td>
 </tr> -->
 <!-- <tr class=xl887473 height=26 style='mso-height-source:userset;height:19.5pt'>
  <td height=26 class=xl1307473 style='height:19.5pt;border-top:none'>Project</td>
  <td class=xl1317473 style='border-top:none;border-left:none'>Project Code</td>
  <td class=xl1327473 style='border-top:none;border-left:none'>Location</td>
  <td class=xl2377473 style='border-top:none'>&nbsp;</td>
  <td class=xl1007473 style='border-top:none'>&nbsp;</td>
  <td class=xl1017473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1027473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1927473 style='border-top:none'>&nbsp;</td>
  <td class=xl1027473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1167473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1017473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1017473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1007473 style='border-top:none'>&nbsp;</td>
  <td class=xl1017473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1017473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1017473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1867473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1017473 style='border-top:none'>&nbsp;</td>
  <td class=xl1017473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1017473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1927473 style='border-top:none'>&nbsp;</td>
  <td class=xl1927473 style='border-top:none'>&nbsp;</td>
  <td class=xl1017473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1017473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1017473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1017473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1007473 style='border-top:none'>&nbsp;</td>
  <td class=xl1867473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1017473 style='border-top:none'>&nbsp;</td>
  <td class=xl1017473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1017473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1017473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1337473>&nbsp;</td>
  <td class=xl1007473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1017473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1027473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1027473 style='border-top:none'>&nbsp;</td>
  <td class=xl1337473>&nbsp;</td>
  <td class=xl1027473 style='border-top:none'>&nbsp;</td>
  <td class=xl1337473>&nbsp;</td>
  <td class=xl887473></td>
  <td class=xl887473></td>
  <td class=xl887473></td>
  <td class=xl887473></td>
 </tr> -->
 <!-- <tr class=xl897473 height=31 style='mso-height-source:userset;height:23.25pt'>
  <td height=31 class=xl1357473 style='height:23.25pt'>Common A.A</td>
  <td class=xl1057473 style='border-left:none'>23CCP1</td>
  <td class=xl1057473 style='border-left:none'>A.A</td>
  <td class=xl2147473 width=37 style='width:28pt'>4.5</td>
  <td class=xl1367473>&nbsp;</td>
  <td class=xl2127473 style='border-left:none'>&nbsp;</td>
  <td class=xl1377473 style='border-left:none'>&nbsp;</td>
  <td class=xl1387473 width=37 style='width:28pt'>8.5</td>
  <td class=xl1387473 width=37 style='width:28pt'>8.5</td>
  <td class=xl1397473 width=37 style='border-left:none;width:28pt'>8.5</td>
  <td class=xl2397473 width=37 style='border-left:none;width:28pt'>4.5</td>
  <td class=xl2127473 style='border-left:none'>&nbsp;</td>
  <td class=xl1367473>&nbsp;</td>
  <td class=xl1397473 width=37 style='border-left:none;width:28pt'>8.5</td>
  <td class=xl1397473 width=37 style='border-left:none;width:28pt'>8.5</td>
  <td class=xl1397473 width=37 style='border-left:none;width:28pt'>8.5</td>
  <td class=xl2117473 width=37 style='border-left:none;width:28pt'>8.5</td>
  <td class=xl2397473 width=37 style='width:28pt'>4.5</td>
  <td class=xl2127473 style='border-left:none'>&nbsp;</td>
  <td class=xl2127473 style='border-left:none'>&nbsp;</td>
  <td class=xl2137473 width=37 style='width:28pt'>8.5</td>
  <td class=xl2137473 width=37 style='width:28pt'>8.5</td>
  <td class=xl1397473 width=37 style='border-left:none;width:28pt'>8.5</td>
  <td class=xl1397473 width=37 style='border-left:none;width:28pt'>8.5</td>
  <td class=xl2397473 width=37 style='border-left:none;width:28pt'>4.5</td>
  <td class=xl2127473 style='border-left:none'>&nbsp;</td>
  <td class=xl1367473>&nbsp;</td>
  <td class=xl2117473 width=37 style='border-left:none;width:28pt'>8.5</td>
  <td class=xl1397473 width=37 style='width:28pt'>8.5</td>
  <td class=xl1397473 width=37 style='border-left:none;width:28pt'>8.5</td>
  <td class=xl1397473 width=37 style='border-left:none;width:28pt'>8.5</td>
  <td class=xl2397473 width=37 style='border-left:none;width:28pt'>4.5</td>
  <td class=xl1407473>&nbsp;</td>
  <td class=xl1367473 style='border-left:none'>&nbsp;</td>
  <td class=xl1397473 width=37 style='border-left:none;width:28pt'>8.5</td>
  <td class=xl1387473 width=39 style='width:29pt'>8.5</td>
  <td class=xl1387473 width=39 style='width:29pt'>8.5</td>
  <td class=xl1407473>&nbsp;</td>
  <td class=xl1387473 width=39 style='width:29pt'>4.5</td>
  <td class=xl1407473>&nbsp;</td>
  <td class=xl2007473 style='border-top:none'>180.0</td>
 </tr> -->
 <!-- <tr height=31 style='mso-height-source:userset;height:23.25pt'>
  <td height=31 class=xl1457473 style='height:23.25pt;border-top:none'>&nbsp;</td>
  <td class=xl1057473 style='border-left:none'><span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl1037473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2187473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1467473 style='border-top:none'>&nbsp;</td>
  <td class=xl1417473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1477473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1487473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1487473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2407473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1417473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1467473 style='border-top:none'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2167473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2407473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1417473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1417473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2177473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl2177473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2407473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1417473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1467473 style='border-top:none'>&nbsp;</td>
  <td class=xl2167473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2407473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1507473 style='border-top:none'>&nbsp;</td>
  <td class=xl1467473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1507473 style='border-top:none'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1507473 style='border-top:none'>&nbsp;</td>
  <td class=xl2007473 style='border-top:none'>0.0</td>
 </tr>
 <tr height=31 style='mso-height-source:userset;height:23.25pt'>
  <td height=31 class=xl1457473 style='height:23.25pt;border-top:none'>&nbsp;</td>
  <td class=xl1057473 style='border-left:none'><span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl1037473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2187473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1467473 style='border-top:none'>&nbsp;</td>
  <td class=xl1417473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1477473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1487473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1487473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2407473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1417473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1467473 style='border-top:none'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2167473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2407473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1417473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1417473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2177473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl2177473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2407473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1417473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1467473 style='border-top:none'>&nbsp;</td>
  <td class=xl2167473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2407473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1507473 style='border-top:none'>&nbsp;</td>
  <td class=xl1467473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1507473 style='border-top:none'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1507473 style='border-top:none'>&nbsp;</td>
  <td class=xl2007473 style='border-top:none'>0.0</td>
 </tr>
 <tr height=31 style='mso-height-source:userset;height:23.25pt'>
  <td height=31 class=xl1457473 style='height:23.25pt;border-top:none'>&nbsp;</td>
  <td class=xl1057473 style='border-left:none'><span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl1037473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2187473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1467473 style='border-top:none'>&nbsp;</td>
  <td class=xl1417473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1477473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1487473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1487473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2407473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1417473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1467473 style='border-top:none'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2167473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2407473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1417473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1417473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2177473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl2177473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2407473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1417473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1467473 style='border-top:none'>&nbsp;</td>
  <td class=xl2167473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2407473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1507473 style='border-top:none'>&nbsp;</td>
  <td class=xl1467473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1507473 style='border-top:none'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1507473 style='border-top:none'>&nbsp;</td>
  <td class=xl2007473 style='border-top:none'>0.0</td>
 </tr>
 <tr height=31 style='mso-height-source:userset;height:23.25pt'>
  <td height=31 class=xl1457473 style='height:23.25pt;border-top:none'>&nbsp;</td>
  <td class=xl1057473 style='border-left:none'><span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl1037473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2187473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1467473 style='border-top:none'>&nbsp;</td>
  <td class=xl1417473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1477473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1487473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1487473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2407473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1417473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1467473 style='border-top:none'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2167473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2407473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1417473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1417473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2177473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl2177473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2407473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1417473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1467473 style='border-top:none'>&nbsp;</td>
  <td class=xl2167473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2407473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1507473 style='border-top:none'>&nbsp;</td>
  <td class=xl1467473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1507473 style='border-top:none'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1507473 style='border-top:none'>&nbsp;</td>
  <td class=xl2007473 style='border-top:none'>0.0</td>
 </tr>
 <tr height=31 style='mso-height-source:userset;height:23.25pt'>
  <td height=31 class=xl1457473 style='height:23.25pt;border-top:none'>&nbsp;</td>
  <td class=xl1057473 style='border-left:none'><span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl1037473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2187473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1467473 style='border-top:none'>&nbsp;</td>
  <td class=xl1417473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1477473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1487473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1487473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2407473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1417473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1467473 style='border-top:none'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2167473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2407473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1417473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1417473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2177473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl2177473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2407473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1417473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1467473 style='border-top:none'>&nbsp;</td>
  <td class=xl2167473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2407473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1507473 style='border-top:none'>&nbsp;</td>
  <td class=xl1467473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1507473 style='border-top:none'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1507473 style='border-top:none'>&nbsp;</td>
  <td class=xl2007473 style='border-top:none'>0.0</td>
 </tr>
 <tr height=31 style='mso-height-source:userset;height:23.25pt'>
  <td height=31 class=xl1517473 style='height:23.25pt;border-top:none'>&nbsp;</td>
  <td class=xl1057473 style='border-left:none'><span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl1067473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2217473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1527473 style='border-top:none'>&nbsp;</td>
  <td class=xl1577473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1537473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1547473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1547473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1557473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2417473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1577473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1527473 style='border-top:none'>&nbsp;</td>
  <td class=xl1557473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1557473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1557473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2197473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2417473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1577473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1577473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2207473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl2207473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1557473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1557473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2417473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1577473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1527473 style='border-top:none'>&nbsp;</td>
  <td class=xl2197473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1557473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1557473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1557473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2417473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1567473 style='border-top:none'>&nbsp;</td>
  <td class=xl1527473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1557473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl1547473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1547473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1567473 style='border-top:none'>&nbsp;</td>
  <td class=xl1547473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1567473 style='border-top:none'>&nbsp;</td>
  <td class=xl2007473 style='border-top:none'>0.0</td>
 </tr> -->
 <!-- <tr height=34 style='mso-height-source:userset;height:25.5pt'>
  <td height=34 class=xl1077473 width=99 style='height:25.5pt;width:74pt'>Sub
  Total <br>
    Working days</td>
  <td class=xl1087473 style='border-left:none'><span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl1087473 style='border-left:none'>&nbsp;</td>
  <td class=xl1877473 width=37 style='border-left:none;width:28pt'>4.5</td>
  <td class=xl777473 width=37 style='width:28pt'>0</td>
  <td class=xl787473 width=37 style='border-left:none;width:28pt'>0</td>
  <td class=xl847473 width=37 style='border-left:none;width:28pt'>0</td>
  <td class=xl1937473 width=37 style='width:28pt'>8.5</td>
  <td class=xl797473 width=37 style='border-left:none;width:28pt'>8.5</td>
  <td class=xl787473 width=37 style='border-left:none;width:28pt'>8.5</td>
  <td class=xl797473 width=37 style='border-left:none;width:28pt'>4.5</td>
  <td class=xl787473 width=37 style='border-left:none;width:28pt'>0</td>
  <td class=xl777473 width=37 style='width:28pt'>0</td>
  <td class=xl797473 width=37 style='border-left:none;width:28pt'>8.5</td>
  <td class=xl797473 width=37 style='border-left:none;width:28pt'>8.5</td>
  <td class=xl797473 width=37 style='border-left:none;width:28pt'>8.5</td>
  <td class=xl1977473 width=37 style='border-left:none;width:28pt'>8.5</td>
  <td class=xl797473 width=37 style='width:28pt'>4.5</td>
  <td class=xl787473 width=37 style='border-left:none;width:28pt'>0</td>
  <td class=xl787473 width=37 style='border-left:none;width:28pt'>0</td>
  <td class=xl1937473 width=37 style='width:28pt'>8.5</td>
  <td class=xl1937473 width=37 style='width:28pt'>8.5</td>
  <td class=xl797473 width=37 style='border-left:none;width:28pt'>8.5</td>
  <td class=xl797473 width=37 style='border-left:none;width:28pt'>8.5</td>
  <td class=xl797473 width=37 style='border-left:none;width:28pt'>4.5</td>
  <td class=xl787473 width=37 style='border-left:none;width:28pt'>0</td>
  <td class=xl777473 width=37 style='width:28pt'>0</td>
  <td class=xl1977473 width=37 style='border-left:none;width:28pt'>8.5</td>
  <td class=xl797473 width=37 style='width:28pt'>8.5</td>
  <td class=xl797473 width=37 style='border-left:none;width:28pt'>8.5</td>
  <td class=xl797473 width=37 style='border-left:none;width:28pt'>8.5</td>
  <td class=xl797473 width=37 style='border-left:none;width:28pt'>4.5</td>
  <td class=xl787473 width=37 style='border-left:none;width:28pt'>0</td>
  <td class=xl777473 width=37 style='width:28pt'>0</td>
  <td class=xl797473 width=37 style='border-left:none;width:28pt'>8.5</td>
  <td class=xl797473 width=39 style='border-left:none;width:29pt'>8.5</td>
  <td class=xl797473 width=39 style='border-left:none;width:29pt'>8.5</td>
  <td class=xl787473 width=39 style='border-left:none;width:29pt'>0</td>
  <td class=xl797473 width=39 style='border-left:none;width:29pt'>4.5</td>
  <td class=xl787473 width=39 style='border-left:none;width:29pt'>0</td>
  <td class=xl2017473 width=43 style='width:32pt'>180.00</td>
 </tr> -->
 <!-- <tr height=27 style='mso-height-source:userset;height:20.25pt'>
  <td height=27 class=xl1097473 style='height:20.25pt;border-top:none'>LEAVE</td>
  <td class=xl1107473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1107473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1887473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl817473 style='border-top:none'>&nbsp;</td>
  <td class=xl827473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl857473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1947473 style='border-top:none'>&nbsp;</td>
  <td class=xl827473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1117473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl827473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl827473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl817473 style='border-top:none'>&nbsp;</td>
  <td class=xl827473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl827473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl827473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1887473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl827473 style='border-top:none'>&nbsp;</td>
  <td class=xl827473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl827473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1947473 style='border-top:none'>&nbsp;</td>
  <td class=xl1947473 style='border-top:none'>&nbsp;</td>
  <td class=xl827473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl827473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl827473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl827473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl817473 style='border-top:none'>&nbsp;</td>
  <td class=xl1887473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl827473 style='border-top:none'>&nbsp;</td>
  <td class=xl827473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl827473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl827473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl827473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl817473 style='border-top:none'>&nbsp;</td>
  <td class=xl827473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl827473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl827473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl827473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl827473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl827473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2027473 style='border-top:none'>0</td>
 </tr> -->
 <!-- <tr height=33 style='mso-height-source:userset;height:24.75pt'>
  <td height=33 class=xl687473 style='height:24.75pt'>Sick leave</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>
  <td class=xl2147473 width=37 style='width:28pt'>&nbsp;</td>
  <td class=xl1657473>&nbsp;</td>
  <td class=xl1707473 style='border-left:none'>&nbsp;</td>
  <td class=xl1667473 style='border-left:none'>&nbsp;</td>
  <td class=xl1387473 width=37 style='width:28pt'>&nbsp;</td>
  <td class=xl1387473 width=37 style='width:28pt'>&nbsp;</td>
  <td class=xl1677473 width=37 style='border-left:none;width:28pt'>&nbsp;</td>
  <td class=xl2427473 style='border-left:none'>&nbsp;</td>
  <td class=xl1707473 style='border-left:none'>&nbsp;</td>
  <td class=xl1657473>&nbsp;</td>
  <td class=xl1687473 style='border-left:none'>&nbsp;</td>
  <td class=xl1687473 style='border-left:none'>&nbsp;</td>
  <td class=xl1687473 style='border-left:none'>&nbsp;</td>
  <td class=xl2237473 style='border-left:none'>&nbsp;</td>
  <td class=xl2427473>&nbsp;</td>
  <td class=xl1707473 style='border-left:none'>&nbsp;</td>
  <td class=xl1707473 style='border-left:none'>&nbsp;</td>
  <td class=xl2247473>&nbsp;</td>
  <td class=xl2247473>&nbsp;</td>
  <td class=xl1687473 style='border-left:none'>&nbsp;</td>
  <td class=xl1687473 style='border-left:none'>&nbsp;</td>
  <td class=xl2427473 style='border-left:none'>&nbsp;</td>
  <td class=xl1707473 style='border-left:none'>&nbsp;</td>
  <td class=xl1657473>&nbsp;</td>
  <td class=xl2237473 style='border-left:none'>&nbsp;</td>
  <td class=xl1687473>&nbsp;</td>
  <td class=xl1687473 style='border-left:none'>&nbsp;</td>
  <td class=xl1687473 style='border-left:none'>&nbsp;</td>
  <td class=xl2427473 style='border-left:none'>&nbsp;</td>
  <td class=xl1697473>&nbsp;</td>
  <td class=xl1657473 style='border-left:none'>&nbsp;</td>
  <td class=xl1687473 style='border-left:none'>&nbsp;</td>
  <td class=xl1387473 width=39 style='width:29pt'>&nbsp;</td>
  <td class=xl1387473 width=39 style='width:29pt'>&nbsp;</td>
  <td class=xl1697473>&nbsp;</td>
  <td class=xl1387473 width=39 style='width:29pt'>&nbsp;</td>
  <td class=xl1697473>&nbsp;</td>
  <td class=xl2037473>0.0</td>
 </tr> -->
 <!-- <tr height=33 style='mso-height-source:userset;height:24.75pt'>
  <td height=33 class=xl697473 style='height:24.75pt;border-top:none'>Maternity
  Leave</td>
  <td class=xl1037473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1037473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2187473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1717473 style='border-top:none'>&nbsp;</td>
  <td class=xl1757473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1727473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1487473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1487473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2437473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1757473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1717473 style='border-top:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2267473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2437473 style='border-top:none'>&nbsp;</td>
  <td class=xl1757473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1757473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2277473 style='border-top:none'>&nbsp;</td>
  <td class=xl2277473 style='border-top:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2437473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1757473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1717473 style='border-top:none'>&nbsp;</td>
  <td class=xl2267473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2437473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1747473 style='border-top:none'>&nbsp;</td>
  <td class=xl1717473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1747473 style='border-top:none'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1747473 style='border-top:none'>&nbsp;</td>
  <td class=xl2037473>0.0</td>
 </tr>
 <tr height=33 style='mso-height-source:userset;height:24.75pt'>
  <td height=33 class=xl697473 style='height:24.75pt;border-top:none'>Paternity
  Leave</td>
  <td class=xl1037473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1037473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2187473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1717473 style='border-top:none'>&nbsp;</td>
  <td class=xl1757473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1727473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1487473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1487473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2437473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1757473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1717473 style='border-top:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2267473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2437473 style='border-top:none'>&nbsp;</td>
  <td class=xl1757473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1757473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2277473 style='border-top:none'>&nbsp;</td>
  <td class=xl2277473 style='border-top:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2437473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1757473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1717473 style='border-top:none'>&nbsp;</td>
  <td class=xl2267473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2437473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1747473 style='border-top:none'>&nbsp;</td>
  <td class=xl1717473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1747473 style='border-top:none'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1747473 style='border-top:none'>&nbsp;</td>
  <td class=xl2037473>0.0</td>
 </tr>
 <tr height=33 style='mso-height-source:userset;height:24.75pt'>
  <td height=33 class=xl697473 style='height:24.75pt;border-top:none'>Family
  Leave</td>
  <td class=xl1037473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1037473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2187473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1767473 style='border-top:none'>&nbsp;</td>
  <td class=xl2297473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1777473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1487473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1487473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2437473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2297473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1767473 style='border-top:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2267473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2437473 style='border-top:none'>&nbsp;</td>
  <td class=xl2297473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2297473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2277473 style='border-top:none'>&nbsp;</td>
  <td class=xl2277473 style='border-top:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2437473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2297473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1767473 style='border-top:none'>&nbsp;</td>
  <td class=xl2267473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2437473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1747473 style='border-top:none'>&nbsp;</td>
  <td class=xl1767473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1747473 style='border-top:none'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1747473 style='border-top:none'>&nbsp;</td>
  <td class=xl2037473>0.0</td>
 </tr>
 <tr height=33 style='mso-height-source:userset;height:24.75pt'>
  <td height=33 class=xl697473 style='height:24.75pt;border-top:none'>Public
  Holiday</td>
  <td class=xl1037473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1037473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2187473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1767473 style='border-top:none'>&nbsp;</td>
  <td class=xl2297473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1777473 style='border-top:none;border-left:none'>8.5</td>
  <td class=xl1487473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1487473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2437473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2297473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1767473 style='border-top:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2267473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2437473 style='border-top:none'>&nbsp;</td>
  <td class=xl2297473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2297473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2277473 style='border-top:none'>&nbsp;</td>
  <td class=xl2277473 style='border-top:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2437473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2297473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1767473 style='border-top:none'>&nbsp;</td>
  <td class=xl2267473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2437473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1747473 style='border-top:none'>&nbsp;</td>
  <td class=xl1767473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1747473 style='border-top:none'>8.5</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1747473 style='border-top:none'>&nbsp;</td>
  <td class=xl2037473>17.0</td>
 </tr>
 <tr height=33 style='mso-height-source:userset;height:24.75pt'>
  <td height=33 class=xl697473 style='height:24.75pt;border-top:none'>Study
  leave</td>
  <td class=xl1037473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1037473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2187473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1717473 style='border-top:none'>&nbsp;</td>
  <td class=xl1757473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1727473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1487473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1487473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2437473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1757473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1717473 style='border-top:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2267473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2437473 style='border-top:none'>&nbsp;</td>
  <td class=xl1757473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1757473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2277473 style='border-top:none'>&nbsp;</td>
  <td class=xl2277473 style='border-top:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2437473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1757473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1717473 style='border-top:none'>&nbsp;</td>
  <td class=xl2267473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2437473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1747473 style='border-top:none'>&nbsp;</td>
  <td class=xl1717473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1747473 style='border-top:none'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1747473 style='border-top:none'>&nbsp;</td>
  <td class=xl2037473>0.0</td>
 </tr>
 <tr height=33 style='mso-height-source:userset;height:24.75pt'>
  <td height=33 class=xl697473 style='height:24.75pt;border-top:none'>Annual
  Leave<span style='mso-spacerun:yes'> </span></td>
  <td class=xl1037473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1037473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2187473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1767473 style='border-top:none'>&nbsp;</td>
  <td class=xl2297473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1777473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1487473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1487473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2437473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2297473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1767473 style='border-top:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2267473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2437473 style='border-top:none'>&nbsp;</td>
  <td class=xl2297473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2297473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2277473 style='border-top:none'>&nbsp;</td>
  <td class=xl2277473 style='border-top:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2437473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2297473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1767473 style='border-top:none'>&nbsp;</td>
  <td class=xl2267473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2437473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1747473 style='border-top:none'>&nbsp;</td>
  <td class=xl1767473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1747473 style='border-top:none'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1747473 style='border-top:none'>&nbsp;</td>
  <td class=xl2037473>0.0</td>
 </tr>
 <tr height=33 style='mso-height-source:userset;height:24.75pt'>
  <td height=33 class=xl737473 width=99 style='height:24.75pt;border-top:none;
  width:74pt'>Floating Holiday</td>
  <td class=xl1037473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1037473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2187473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1717473 style='border-top:none'>&nbsp;</td>
  <td class=xl1757473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1727473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1487473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1487473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1497473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2437473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1757473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1717473 style='border-top:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2267473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2437473 style='border-top:none'>&nbsp;</td>
  <td class=xl1757473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1757473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2277473 style='border-top:none'>&nbsp;</td>
  <td class=xl2277473 style='border-top:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2437473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1757473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1717473 style='border-top:none'>&nbsp;</td>
  <td class=xl2267473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2437473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1747473 style='border-top:none'>&nbsp;</td>
  <td class=xl1717473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1737473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1747473 style='border-top:none'>&nbsp;</td>
  <td class=xl1487473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1747473 style='border-top:none'>&nbsp;</td>
  <td class=xl2037473>0.0</td>
 </tr>
 <tr height=33 style='mso-height-source:userset;height:24.75pt'>
  <td height=33 class=xl707473 width=99 style='height:24.75pt;border-top:none;
  width:74pt'>Other</td>
  <td class=xl1067473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1067473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2217473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1787473 style='border-top:none'>&nbsp;</td>
  <td class=xl1827473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1797473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1547473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1547473 width=37 style='border-top:none;width:28pt'>&nbsp;</td>
  <td class=xl1557473 width=37 style='border-top:none;border-left:none;
  width:28pt'>&nbsp;</td>
  <td class=xl2447473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1827473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1787473 style='border-top:none'>&nbsp;</td>
  <td class=xl1807473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1807473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1807473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2307473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2447473 style='border-top:none'>&nbsp;</td>
  <td class=xl1827473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1827473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2317473 style='border-top:none'>&nbsp;</td>
  <td class=xl2317473 style='border-top:none'>&nbsp;</td>
  <td class=xl1807473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1807473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2447473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1827473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1787473 style='border-top:none'>&nbsp;</td>
  <td class=xl2307473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1807473 style='border-top:none'>&nbsp;</td>
  <td class=xl1807473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1807473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2447473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1817473 style='border-top:none'>&nbsp;</td>
  <td class=xl1787473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1807473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1547473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1547473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1817473 style='border-top:none'>&nbsp;</td>
  <td class=xl1547473 width=39 style='border-top:none;width:29pt'>&nbsp;</td>
  <td class=xl1817473 style='border-top:none'>&nbsp;</td>
  <td class=xl2047473>0.0</td>
 </tr> -->
 <!-- <tr height=29 style='mso-height-source:userset;height:21.75pt'>
  <td height=29 class=xl1177473 style='height:21.75pt'>Sub Total <br>
    Leaves</td>
  <td class=xl1087473 style='border-left:none'>&nbsp;</td>
  <td class=xl1087473 style='border-left:none'>&nbsp;</td>
  <td class=xl1877473 width=37 style='border-left:none;width:28pt'>0</td>
  <td class=xl907473 width=37 style='width:28pt'>0</td>
  <td class=xl797473 width=37 style='border-left:none;width:28pt'>0</td>
  <td class=xl807473 width=37 style='border-left:none;width:28pt'>8.5</td>
  <td class=xl1937473 width=37 style='width:28pt'>0</td>
  <td class=xl797473 width=37 style='border-left:none;width:28pt'>0</td>
  <td class=xl787473 width=37 style='border-left:none;width:28pt'>0</td>
  <td class=xl797473 width=37 style='border-left:none;width:28pt'>0</td>
  <td class=xl797473 width=37 style='border-left:none;width:28pt'>0</td>
  <td class=xl907473 width=37 style='width:28pt'>0</td>
  <td class=xl797473 width=37 style='border-left:none;width:28pt'>0</td>
  <td class=xl797473 width=37 style='border-left:none;width:28pt'>0</td>
  <td class=xl797473 width=37 style='border-left:none;width:28pt'>0</td>
  <td class=xl1877473 width=37 style='border-left:none;width:28pt'>0</td>
  <td class=xl797473 width=37 style='width:28pt'>0</td>
  <td class=xl797473 width=37 style='border-left:none;width:28pt'>0</td>
  <td class=xl797473 width=37 style='border-left:none;width:28pt'>0</td>
  <td class=xl1937473 width=37 style='width:28pt'>0</td>
  <td class=xl1937473 width=37 style='width:28pt'>0</td>
  <td class=xl797473 width=37 style='border-left:none;width:28pt'>0</td>
  <td class=xl797473 width=37 style='border-left:none;width:28pt'>0</td>
  <td class=xl797473 width=37 style='border-left:none;width:28pt'>0</td>
  <td class=xl797473 width=37 style='border-left:none;width:28pt'>0</td>
  <td class=xl907473 width=37 style='width:28pt'>0</td>
  <td class=xl1877473 width=37 style='border-left:none;width:28pt'>0</td>
  <td class=xl797473 width=37 style='width:28pt'>0</td>
  <td class=xl797473 width=37 style='border-left:none;width:28pt'>0</td>
  <td class=xl797473 width=37 style='border-left:none;width:28pt'>0</td>
  <td class=xl797473 width=37 style='border-left:none;width:28pt'>0</td>
  <td class=xl797473 width=37 style='border-left:none;width:28pt'>0</td>
  <td class=xl907473 width=37 style='width:28pt'>0</td>
  <td class=xl797473 width=37 style='border-left:none;width:28pt'>0</td>
  <td class=xl797473 width=39 style='border-left:none;width:29pt'>0</td>
  <td class=xl797473 width=39 style='border-left:none;width:29pt'>0</td>
  <td class=xl797473 width=39 style='border-left:none;width:29pt'>8.5</td>
  <td class=xl797473 width=39 style='border-left:none;width:29pt'>0</td>
  <td class=xl797473 width=39 style='border-left:none;width:29pt'>0</td>
  <td class=xl2057473>17</td>
 </tr> -->
 <!-- <tr height=29 style='mso-height-source:userset;height:21.75pt'>
  <td height=29 class=xl1187473 style='height:21.75pt;border-top:none'>Grand
  Total</td>
  <td class=xl1197473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1197473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1897473 style='border-top:none;border-left:none'>4.5</td>
  <td class=xl917473 style='border-top:none'>0</td>
  <td class=xl937473 style='border-top:none;border-left:none'>0</td>
  <td class=xl927473 style='border-top:none;border-left:none'>8.5</td>
  <td class=xl1957473 style='border-top:none'>8.5</td>
  <td class=xl937473 style='border-top:none;border-left:none'>8.5</td>
  <td class=xl1047473 width=37 style='border-top:none;border-left:none;
  width:28pt'>8.5</td>
  <td class=xl937473 style='border-top:none;border-left:none'>4.5</td>
  <td class=xl937473 style='border-top:none;border-left:none'>0</td>
  <td class=xl917473 style='border-top:none'>0</td>
  <td class=xl937473 style='border-top:none;border-left:none'>8.5</td>
  <td class=xl937473 style='border-top:none;border-left:none'>8.5</td>
  <td class=xl937473 style='border-top:none;border-left:none'>8.5</td>
  <td class=xl1897473 style='border-top:none;border-left:none'>8.5</td>
  <td class=xl937473 style='border-top:none'>4.5</td>
  <td class=xl937473 style='border-top:none;border-left:none'>0</td>
  <td class=xl937473 style='border-top:none;border-left:none'>0</td>
  <td class=xl1957473 style='border-top:none'>8.5</td>
  <td class=xl1957473 style='border-top:none'>8.5</td>
  <td class=xl937473 style='border-top:none;border-left:none'>8.5</td>
  <td class=xl937473 style='border-top:none;border-left:none'>8.5</td>
  <td class=xl937473 style='border-top:none;border-left:none'>4.5</td>
  <td class=xl937473 style='border-top:none;border-left:none'>0</td>
  <td class=xl917473 style='border-top:none'>0</td>
  <td class=xl1897473 style='border-top:none;border-left:none'>8.5</td>
  <td class=xl937473 style='border-top:none'>8.5</td>
  <td class=xl937473 style='border-top:none;border-left:none'>8.5</td>
  <td class=xl937473 style='border-top:none;border-left:none'>8.5</td>
  <td class=xl937473 style='border-top:none;border-left:none'>4.5</td>
  <td class=xl937473 style='border-top:none;border-left:none'>0</td>
  <td class=xl917473 style='border-top:none'>0</td>
  <td class=xl937473 style='border-top:none;border-left:none'>8.5</td>
  <td class=xl937473 style='border-top:none;border-left:none'>8.5</td>
  <td class=xl937473 style='border-top:none;border-left:none'>8.5</td>
  <td class=xl937473 style='border-top:none;border-left:none'>8.5</td>
  <td class=xl937473 style='border-top:none;border-left:none'>4.5</td>
  <td class=xl937473 style='border-top:none;border-left:none'>0</td>
  <td class=xl2067473 style='border-top:none;font-size:10.0pt;color:#9C0006;
  font-weight:400;text-decoration:none;text-underline-style:none;text-line-through:
  none;font-family:Calibri, sans-serif;border-top:.5pt solid windowtext;
  border-right:1.0pt solid windowtext;border-bottom:1.0pt solid windowtext;
  border-left:1.0pt solid windowtext;background:#FFC7CE;mso-pattern:black none'>197</td>
 </tr> -->
 <tr class=xl727473 height=12 style='mso-height-source:userset;height:9.0pt'>
  <td height=12 class=xl2457473 style='height:9.0pt'>&nbsp;</td>
  <td class=xl2467473></td>
  <td class=xl2467473></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2487473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
 </tr>
 <tr class=xl727473 height=26 style='mso-height-source:userset;height:20.1pt'>
  <td height=26 class=xl2457473 style='height:20.1pt'>LOE Allocation</td>
  <td class=xl2467473></td>
  <td class=xl2467473></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2487473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
 </tr>
 <tr class=xl727473 height=26 style='mso-height-source:userset;height:20.1pt'>
  <td height=26 class=xl747473 colspan=2 style='height:20.1pt'>Actual Hours
  Worked</td>
  <td class=xl747473>&nbsp;</td>
  <td colspan=5 class=xl2647473><span style='mso-spacerun:yes'> </span></td>
  <td colspan=5 class=xl2657473><span style='mso-spacerun:yes'> </span></td>
  <td colspan=5 class=xl2337473 width=185 style='width:140pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td colspan=5 class=xl2347473><span style='mso-spacerun:yes'> </span></td>
  <td colspan=5 class=xl2347473><span style='mso-spacerun:yes'> </span></td>
  <td colspan=5 class=xl2347473><span style='mso-spacerun:yes'> </span></td>
  <td colspan=5 class=xl2347473><span style='mso-spacerun:yes'> </span></td>
  <td colspan=5 rowspan=2 class=xl2667473 width=121 style='width:90pt'>&nbsp;</td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
 </tr>
 <tr class=xl727473 height=26 style='mso-height-source:userset;height:20.1pt'>
  <td height=26 class=xl747473 style='height:20.1pt'>&nbsp;</td>
  <td class=xl747473>&nbsp;</td>
  <td class=xl747473>&nbsp;</td>
  <td colspan=2 class=xl2337473 width=74 style='width:56pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td colspan=2 class=xl2337473 width=74 style='width:56pt'>&nbsp;</td>
  <td class=xl717473 width=37 style='width:28pt'>&nbsp;</td>
  <td colspan=2 class=xl2337473 width=74 style='width:56pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td colspan=2 class=xl2337473 width=74 style='width:56pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl2347473>&nbsp;</td>
  <td colspan=2 class=xl2337473 width=74 style='width:56pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td colspan=2 class=xl2337473 width=74 style='width:56pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl2347473>&nbsp;</td>
  <td colspan=2 class=xl2337473 width=74 style='width:56pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td colspan=2 class=xl2337473 width=74 style='width:56pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl2347473>&nbsp;</td>
  <td colspan=2 class=xl2337473 width=74 style='width:56pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td colspan=2 class=xl2337473 width=74 style='width:56pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl2347473>&nbsp;</td>
  <td colspan=2 class=xl2337473 width=74 style='width:56pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td colspan=2 class=xl2337473 width=74 style='width:56pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl2337473 width=37 style='width:28pt'>&nbsp;</td>
  <td colspan=2 class=xl2337473 width=74 style='width:56pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td colspan=2 class=xl2337473 width=78 style='width:58pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl2347473>&nbsp;</td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
 </tr>
 <tr class=xl727473 height=19 style='mso-height-source:userset;height:14.25pt'>
  <td height=19 class=xl2497473 style='height:14.25pt'></td>
  <td class=xl2467473></td>
  <td class=xl2467473></td>
  <td colspan=2 class=xl1857473><span style='mso-spacerun:yes'> </span></td>
  <td class=xl727473></td>
  <td colspan=2 class=xl2517473 width=74 style='width:56pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td colspan=2 class=xl1857473><span style='mso-spacerun:yes'> </span></td>
  <td class=xl2477473></td>
  <td colspan=2 class=xl2527473><span style='mso-spacerun:yes'> </span></td>
  <td colspan=2 class=xl1857473><span style='mso-spacerun:yes'> </span></td>
  <td class=xl2477473></td>
  <td colspan=2 class=xl2527473><span style='mso-spacerun:yes'> </span></td>
  <td colspan=2 class=xl1857473><span style='mso-spacerun:yes'> </span></td>
  <td class=xl2477473></td>
  <td colspan=2 class=xl2527473><span style='mso-spacerun:yes'> </span></td>
  <td colspan=2 class=xl1857473><span style='mso-spacerun:yes'> </span></td>
  <td class=xl2477473></td>
  <td colspan=2 class=xl2527473><span style='mso-spacerun:yes'> </span></td>
  <td colspan=2 class=xl1857473><span style='mso-spacerun:yes'> </span></td>
  <td class=xl2477473></td>
  <td colspan=2 class=xl2517473 width=74 style='width:56pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td colspan=2 class=xl2637473><span style='mso-spacerun:yes'> </span></td>
  <td colspan=3 class=xl2527473><span style='mso-spacerun:yes'> </span></td>
  <td colspan=2 class=xl1857473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2507473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
 </tr>
 <tr class=xl727473 height=19 style='mso-height-source:userset;height:14.25pt'>
  <td colspan=2 height=19 class=xl2607473 style='height:14.25pt'>Total Actual
  Hours Worked</td>
  <td class=xl767473><span style='mso-spacerun:yes'> </span></td>
  <td class=xl1857473></td>
  <td class=xl1857473></td>
  <td class=xl727473></td>
  <td class=xl2517473 width=37 style='width:28pt'></td>
  <td class=xl2517473 width=37 style='width:28pt'></td>
  <td class=xl1857473></td>
  <td class=xl1857473></td>
  <td class=xl2477473></td>
  <td class=xl2527473></td>
  <td class=xl2527473></td>
  <td class=xl1857473></td>
  <td class=xl1857473></td>
  <td class=xl2477473></td>
  <td class=xl2527473></td>
  <td class=xl2527473></td>
  <td class=xl1857473></td>
  <td class=xl1857473></td>
  <td class=xl2477473></td>
  <td class=xl2527473></td>
  <td class=xl2527473></td>
  <td class=xl1857473></td>
  <td class=xl1857473></td>
  <td class=xl2477473></td>
  <td class=xl2527473></td>
  <td class=xl2527473></td>
  <td class=xl1857473></td>
  <td colspan=3 class=xl2617473><?php echo $this->empHolidaysWeekends['holiday_dates']; ?></td>
  <td class=xl2537473 colspan=7><?php echo $this->empHolidaysWeekends['holiday_names']; ?></td>
  <td class=xl1857473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2507473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
 </tr>
 <?php echo build_calendar_Holiday_View(); ?>
 <!-- <tr class=xl727473 height=19 style='mso-height-source:userset;height:14.25pt'>
  <td colspan=2 height=19 class=xl2607473 style='height:14.25pt'>Total LOE<span
  style='mso-spacerun:yes'>  </span>%age</td>
  <td class=xl757473><span style='mso-spacerun:yes'> </span></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl2547473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td colspan=3 class=xl2617473><?php echo $this->empHolidaysWeekends['holiday_dates']; ?></td>
  <td colspan=8 class=xl2627473><?php echo $this->empHolidaysWeekends['holiday_names']; ?></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2487473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
 </tr> -->
 <tr class=xl727473 height=15 style='mso-height-source:userset;height:11.25pt'>
  <td height=15 class=xl1857473 style='height:11.25pt'></td>
  <td class=xl1857473></td>
  <td class=xl757473></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl2547473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td colspan=3 class=xl2617473></td>
  <td class=xl2537473></td>
  <td class=xl2537473></td>
  <td class=xl2537473></td>
  <td class=xl2537473></td>
  <td class=xl2537473></td>
  <td class=xl2537473></td>
  <td class=xl2537473></td>
  <td class=xl2537473></td>
  <td class=xl2537473></td>
  <td class=xl2537473></td>
  <td class=xl2537473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
 </tr>
 <tr class=xl727473 height=21 style='height:15.75pt'>
  <td height=21 class=xl2557473 colspan=6 style='height:15.75pt'>I CERTIFY THAT
  ABOVE IS TRUE AND CORRECT<span style='mso-spacerun:yes'> </span></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2577473>&nbsp;</td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
 </tr>
 <tr class=xl727473 height=26 style='mso-height-source:userset;height:19.5pt'>
  <td colspan=18 height=26 class=xl2677473 style='height:19.5pt'><span
  style='mso-spacerun:yes'>                                                                                        
  </span>Employee</td>
  <td colspan=25 class=xl2587473>Approved<span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
 </tr>
 <tr class=xl655357473 height=32 style='mso-height-source:userset;height:24.0pt'>
  <td height=32 class=xl2567473 colspan=3 style='height:24.0pt'>Signature:_______________________</td>
  <td class=xl655357473></td>
  <td class=xl655357473></td>
  <td class=xl655357473></td>
  <td class=xl655357473></td>
  <td class=xl655357473></td>
  <td class=xl655357473></td>
  <td class=xl655357473></td>
  <td class=xl2567473 colspan=7>Date: ______________________________<span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td colspan=9 class=xl2587473>Signature:_______________________</td>
  <td class=xl2567473></td>
  <td colspan=14 class=xl2677473>Date:-<span style='mso-spacerun:yes'> 
  </span><?php echo date("F d, yy"); ?></td>
  <td class=xl655357473></td>
  <td class=xl655357473></td>
  <td class=xl655357473></td>
  <td class=xl655357473></td>
  <td class=xl655357473></td>
  <td class=xl655357473></td>
 </tr>
 <tr class=xl727473 height=26 style='mso-height-source:userset;height:20.1pt'>
  <td height=26 class=xl727473 style='height:20.1pt'></td>
  <td class=xl897473></td>
  <td class=xl897473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2577473>&nbsp;</td>
  <td class=xl2577473>&nbsp;</td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2577473>&nbsp;</td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=99 style='width:74pt'></td>
  <td width=73 style='width:55pt'></td>
  <td width=66 style='width:50pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=39 style='width:29pt'></td>
  <td width=39 style='width:29pt'></td>
  <td width=39 style='width:29pt'></td>
  <td width=39 style='width:29pt'></td>
  <td width=39 style='width:29pt'></td>
  <td width=0></td>
  <td width=0></td>
  <td width=43 style='width:32pt'></td>
  <td width=0></td>
  <td width=0></td>
  <td width=0></td>
  <td width=0></td>
  <td width=0></td>
  <td width=64 style='width:48pt'></td>
 </tr>
 <![endif]>
</table>

</div>
<script type="text/javascript" language="javascript">
$(document).ready(function(){
	$('.breadcrumbs').append("<span class='arrows'>&rsaquo;</span><a href='<?php echo BASE_URL; ?>timemanagement/timesheetreport'>Time Sheet Report</a>");
});
</script>

<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>

</html>
