<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
 	

if (count($this->messages)) {?>
	<div id="dispmsgemp" class="settingssuccess">
		<?php 
			foreach ($this->messages as $message)
			{
				$flag = array();				
				$flag = array_keys($message);
				echo "<div id='messageData' class='ml-alert-1-$flag[0]'><div style='display:block;'><span class='style-1-icon $flag[0]'></span>";
				echo $message[$flag[0]];
				echo "</div></div>";
			} 
		?>
	</div>	
	
<?php }	
if($this->dataArray[0]['emptyroles'] == 1)
{
 ?>
	 <div class="ml-alert-1-info m1-info-set">
		<div class="style-1-icon info"></div>
			Add Employees grid will not work as Roles are not added yet.
	</div>
 <?php	} else	{	?>

<?php
if($this->call != 'ajaxcall')
{
    if(!empty($this->popConfigPermission))
    {
?>
<!--<div>

 For excel Upload 
<div class="profile-tabs-right-2">
    <div class="flt_right">
      	
        <div class="actions_div">
		<span class="uploadbut_exel uploadbutsel flt_left marginfiv" id="upload_custom_div" >Import Employees</span>
		<a target="_blank" href="<?php echo DOMAIN; ?>public/downloads/import_employees.xlsx" class="importformatlink flt_left">Import format</a>
		<a target="_blank" href="<?php echo DOMAIN; ?>public/downloads/importguide.pdf" class="importformatlink flt_left">Help</a>
		<div id="loaderimgprofile" style="display:none;"><img src="<?php echo DOMAIN; ?>public/media/images/loaderwhite_21X21.gif" style="width:21px; height: 21px; float: none; "/></div>								
        </div>                 					
    </div>
    <input type="hidden" id="uploadimagepath" name="uploadimagepath" value=""/>
    <input type="hidden" name="emp_excel" value=""/>							    	
               				                        					
</div>
</div>-->

<span id="error_message"></span>
<div id="upload_error" style="display:none;clear:both;"></div>	
<!-- End excel Upload -->
<?php
    }
}
?>
<input type="hidden" id="reportsView" name="reportsView" value="leave" />
<input type="hidden" id="start_hidden" name="start_hidden"  maxlength="30" size="20" value="<?php echo $this->start_date;?>">  
<input type="hidden" id="end_hidden" name="end_hidden"  maxlength="30" size="20" value="<?php echo $this->end_date;?>"> 
<input type="hidden" id="period_flag" name="period_flag" value="projreports"/>
<input type="hidden" id="is_pdf" name="is_pdf" value="0"/>
<input type="hidden" id="is_excel" name="is_excel" value="0"/>
<input type="hidden" id="sort_order" name="sort_order" value="" />
<input type="hidden" id="sort_by" name="sort_by" value="" />
<input type="hidden" id="page_no" name="page_no" value="" />
<input type="hidden" id="per_page" name="per_page" value="" />
<input type="hidden" id="search_data_pdf" name="search_data_pdf" value="" />
<input type="hidden" id="selected_period_hidden" value="<?php echo $this->selected_period_hidden;?>"/>
<?php
 echo "<div><p>From: <input type=\"text\" id=\"fromdatepicker\"> To: <input type=\"text\" id=\"todatepicker\"></p></div><div class=\"export-links\">
			<div class=\"fltright export_links\">
				<div class=\"sprite export-xls\" name=\"excel\" id=\"excel\">Export to Excel</div>
				<div class=\"sprite export-pdf\" name=\"pdf\" id=\"pdf\">Export to PDF</div>
			</div>
		</div>";

if($this->call == 'ajaxcall'){
	$div = ''; $endDiv = ''; 
} else { 
	$div = '<div id="grid_'.$this->dataArray[0]['objectname'].'" class="all-grid-control">'; $endDiv = '</div>';
}
	echo $div.'<div id="msg" style="display:none;font-style: oblique; font-weight: bold; color: green;""></div><div id="meme">'.$this->employeegrid($this->dataArray[0]).'</div>'.$endDiv;
?>
<?php	}	?>
<script type='text/javascript'>
$(document).ready(function(){
	$( "#fromdatepicker" ).datepicker().datepicker("setDate", new Date());
	$( "#todatepicker" ).datepicker().datepicker("setDate", new Date());
	$("a:contains(leave entitlement per year)").hover(function() {
        $(this).css('cursor','pointer').attr('title', 'Discription Text');
    }, function() {
        $(this).css('cursor','auto');
    });
	$("a:contains(Service Year)").hover(function() {
        $(this).css('cursor','pointer').attr('title', 'Discription Text');
    }, function() {
        $(this).css('cursor','auto');
    });
	$("a:contains(Accrued Leave as of today)").hover(function() {
        $(this).css('cursor','pointer').attr('title', 'Discription Text');
    }, function() {
        $(this).css('cursor','auto');
    });
	$("a:contains(BBF (Balance Brought Forward))").hover(function() {
        $(this).css('cursor','pointer').attr('title', 'Discription Text');
    }, function() {
        $(this).css('cursor','auto');
    });
	$("a:contains(Balance as of today)").hover(function() {
        $(this).css('cursor','pointer').attr('title', 'Discription Text');
    }, function() {
        $(this).css('cursor','auto');
    });
	$("a:contains(Used Leaves)").hover(function() {
        $(this).css('cursor','pointer').attr('title', 'Discription Text');
    }, function() {
        $(this).css('cursor','auto');
    });
	$("a:contains(Leave Balance)").hover(function() {
        $(this).css('cursor','pointer').attr('title', 'Discription Text');
    }, function() {
        $(this).css('cursor','auto');
    });
	$("a:contains(Date of joining)").hover(function() {
        $(this).css('cursor','pointer').attr('title', 'Discription Text');
    }, function() {
        $(this).css('cursor','auto');
    });

    function getEmployeeReports(){
	var projid = $('#idselproj').val();
	var start_date = $('#start_date').val();
	var end_date = $('#end_date').val();
	var selected_period_hidden = $("#selected_period_hidden").attr('value');
	var is_pdf = $('#is_pdf').val();
	var is_excel = $('#is_excel').val();

	if(is_pdf == 1 || is_excel == 1)
	{
		var sort_order = $('#sort_order').val(); 
		var sort_by = $('#sort_by').val(); 
		var page_no = $('#page_no').val(); 
		var per_page = $('#per_page').val();
		var search_data_pdf = $('#search_data_pdf').val();
		var datefrom = $('#fromdatepicker').val();
		var dateto = $('#todatepicker').val();
		datefrom = "-"+new Date(datefrom).getDay()+"-"+new Date(datefrom).getDate();
		dateto = "-"+new Date(dateto).getDay()+"-"+new Date(dateto).getDate();
		// alert(datefrom);
		// alert(start_date);
		$('#is_pdf').val('0');
		$('#is_excel').val('0');
		$('#sort_order').val('');
		$('#sort_by').val('');
		$('#page_no').val('');
		$('#per_page').val('');
		window.location.href = base_url+"/timemanagement/reports/addemployeeleavereports/"+'projectId/'+projid+'/start_date/'+start_date+'/end_date/'+end_date+'/selected_period_hidden/'+selected_period_hidden+'/is_pdf/'+is_pdf+'/is_excel/'+is_excel+'/sort_order/'+sort_order+'/sort_by/'+sort_by+'/page_no/'+page_no+'/per_page/'+per_page+'/search_data_pdf/'+search_data_pdf+'/datefrom/'+datefrom+'/dateto/'+dateto;
	}
	else
	{
		$.ajax({
	    	url: base_url+"/timemanagement/reports/employeereports/format/html",   
	        type : 'POST',	
	        dataType:'html',
	        data :'projectId='+projid+'&start_date='+start_date+'&end_date='+end_date+'&selected_period_hidden='+selected_period_hidden+'&is_pdf='+is_pdf,
	        success : function(response){
	        	$("#idacc_content").html(response);
	        	$(".export_links").show(); 
	        }
	    });		
	}
	
}

    $("#pdf").click(function(){
		var report = $("#reportsView").val();
		$("#is_pdf").val('1');		
		var period = $("#selected_period_hidden").val();
		if(period.trim().length > 0 && (report == 'leave' || report == 'projects'))
		{
			getOnchangeDates();
		}
		else if(report == 'leave')
		{
			getEmployeeReports();
		}
		else
		{
			getProjectReports();
		}
	});

	$("#excel").click(function(){
		var report = $("#reportsView").val();
		$("#is_excel").val('1');		
		var period = $("#selected_period_hidden").val();
		if(period.trim().length > 0 && (report == 'leave' || report == 'projects'))
		{
			getOnchangeDates();
		}
		else if(report == 'leave')
		{
			getEmployeeReports();
		}
		else
		{
			getProjectReports();
		}
	});
<?php if (count($this->messages)) {?>
      setTimeout(function(){
			$('#dispmsgemp').fadeOut('slow');
		},3000);

<?php } ?>

});
</script>


