<?php

function build_calendar($month,$year,$dateArray,$TMSCData,$TimesheetData,$holidays,$holidays0,$leaves) {

     // Create array containing abbreviations of days of week.
     $daysOfWeek = array('S','M','T','W','T','F','S','S','M','T','W','T','F','S','S','M','T','W','T','F','S','S','M','T','W','T','F','S','S','M','T','W','T','F','S');

     // What is the first day of the month in question?
     $firstDayOfMonth = mktime(0,0,0,$month,1,$year);

     // How many days does this month contain?
     $numberDays = date('t',$firstDayOfMonth);

     // Retrieve some information about the first day of the
     // month in question.
     $dateComponents = getdate($firstDayOfMonth);

     // What is the name of the month in question?
     $monthName = $dateComponents['month'];
     $monthNameL = date("F", strtotime($TMSCData[0]['form']));
     $yearNameL = date("Y", strtotime($TMSCData[0]['form']));

     // What is the index value (0-6) of the first day of the
     // month in question.
     $dayOfWeek = $dateComponents['wday'];

     // Create the table tag opener and day headers

     $calendar = "<table id='calendar'>";
     $calendar .= "<caption class='month'>$monthNameL $yearNameL Actual Time ";
     $calendar .= "$monthName $year Actual Time ";
     $calendar .= "$monthName $year Estimated Time</caption>";
     $calendar .= "<tr>";

     // Create the calendar headers

     // foreach($daysOfWeek as $day) {
     //      $calendar .= "<th class='header'>$day</th>";
     // } 

     // Create the rest of the calendar

     // Initiate the day counter, starting with the 1st.

     $currentDay = 1;

     $calendar .= "</tr><tr class = 'weekdays'>";

     // The variable $dayOfWeek is used to
     // ensure that the calendar
     // display consists of exactly 7 columns.

     // if ($dayOfWeek > 0) { 
     //      $calendar .= "<td colspan='$dayOfWeek'>&nbsp;</td>"; 
     // }
     
     $month = str_pad($month, 2, "0", STR_PAD_LEFT);

     $currentDayL = date("d", strtotime($TMSCData[0]['form']));
     $numberDaysL = date("t", strtotime($TMSCData[0]['form']));
     $dayOfWeekL = 0;
     $monthL = date("m", strtotime($TMSCData[0]['form']));
     $yearL = date("Y", strtotime($TMSCData[0]['form']));
     $calendarL = "<tr>";

     if(count($holidays)>0){
          $holiday_names = explode(',', $holidays[0]['holiday_names']);
          $holiday_dates = explode(',', $holidays[0]['holiday_dates']);
     }
     if (count($holidays0)>0) {
          $holiday_names0 = explode(',', $holidays0[0]['holiday_names']);
          $holiday_dates0 = explode(',', $holidays0[0]['holiday_dates']);
     }
     // var_dump($leaves);
     // die();

     // var_dump(date("F", strtotime($TMSCData[0]['form'])));

     while ($currentDayL <= $numberDaysL) {

          // Seventh column (Saturday) reached. Start a new row.

          // if ($dayOfWeek == 30) {

          //      $dayOfWeek = 0;
          //      $calendar .= "</tr><tr>";

          // }
          
          $currentDayRel = str_pad($currentDayL, 2, "0", STR_PAD_LEFT);
          
          $date = "$yearL-$monthL-$currentDayRel";
          $get_name = date('l', strtotime($date)); //get week day
          $day_name = substr($get_name, 0, 3); // Trim day name to 3 chars

          $calendar .= "<td class='day $day_name head' rel='$date'><b>$day_name</b> <div>$currentDayL</div></td>";

          $leave_signal = false;
          foreach ($leaves as $key => $value) {
               if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavestatus']=='Approved')
               {
                    $leave_signal=true;
                    break;
               }
          }

          $date = "&quot;$yearL-$monthL-$currentDayRel&quot;";

          $holiday_signal = false;
          foreach ($holiday_dates as $key => $value) {
               if("&quot;".$value."&quot;"==$date){
                    $holiday_signal=true;
               }
          }
          $sizeofArray = 0;
          foreach ($TimesheetData as $key => $value) {
               $d=strtotime($value['date']);
               $vd = date("Y-m-d", $d);
               if (!$leave_signal&&!$holiday_signal&&"&quot;".$vd."&quot;"==$date && $day_name!='Sun' && $day_name != 'Sat') {
                    $calendarL .= "<td class='day $day_name' id='form'>{$value['duration']}</td>";
                    break;
               }else if (!$leave_signal&&!$holiday_signal&&"&quot;".$vd."&quot;"==$date && ($day_name=='Sun' || $day_name == 'Sat')) {
                    $calendarL .= "<td class='day $day_name' id='form' onclick='TimeSheetForm($date)'>&nbsp; &nbsp;</td>";
               }

               if (!$leave_signal&&!$holiday_signal&&$sizeofArray==count($TimesheetData) && ($day_name!='Sun' && $day_name != 'Sat')) {
                    $calendarL .= "<td class='day $day_name' id='form' onclick='TimeSheetForm($date)'>NA</td>";
               }else if (!$leave_signal&&!$holiday_signal&&$sizeofArray==count($TimesheetData) && ($day_name=='Sun' || $day_name == 'Sat')) {
                    $calendarL .= "<td class='day $day_name' id='form'>&nbsp; &nbsp;</td>";
               }
               if(!$leave_signal&&$holiday_signal){
                    $calendarL .= "<td class='day $day_name' id='form'>&nbsp; H &nbsp;</td>";
                    break;
               }else if($leave_signal){
                    $calendarL .= "<td class='day $day_name' id='form'>&nbsp; L &nbsp;</td>";
                    break;
               }
               $sizeofArray++;
          }

          // Increment counters
 
          $currentDayL++;
          $dayOfWeekL++;

     }


     while ($currentDay <= $numberDays) {

          // Seventh column (Saturday) reached. Start a new row.

          // if ($dayOfWeek == 30) {

          //      $dayOfWeek = 0;
          //      $calendar .= "</tr><tr>";

          // }
          
          $currentDayRel = str_pad($currentDay, 2, "0", STR_PAD_LEFT);
          
          $date = "$year-$month-$currentDayRel";
          $get_name = date('l', strtotime($date)); //get week day
          $day_name = substr($get_name, 0, 3); // Trim day name to 3 chars

          $calendar .= "<td class='day $day_name head' rel='$date'><b>$day_name</b> <div>$currentDay</div></td>";
          // $calendarL .= "<td class='day $day_name' rel='$date' id='form'>00:00</td>";

          $leave_signal = false;
          foreach ($leaves as $key => $value) {
               if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavestatus']=='Approved')
               {
                    $leave_signal=true;
                    break;
               }
          }

          $date = "&quot;$year-$month-$currentDayRel&quot;";

          $holiday_signal = false;
          foreach ($holiday_dates0 as $key => $value) {
               if("&quot;".$value."&quot;"==$date){
                    $holiday_signal=true;
               }
          }
          $sizeofArray = 1;
          foreach ($TimesheetData as $key => $value) {
               $d=strtotime($value['date']);
               $vd = date("Y-m-d", $d);
               if (!$leave_signal&&!$holiday_signal&&"&quot;".$vd."&quot;"==$date && ($day_name!='Sun' || $day_name != 'Sat')) {
                    $calendarL .= "<td class='day $day_name' id='form' onclick='TimeSheetForm($date)'>{$value['duration']}</td>";
                    break;
               }else if (!$leave_signal&&!$holiday_signal&&"&quot;".$vd."&quot;"==$date && ($day_name=='Sun' || $day_name == 'Sat')) {
                    $calendarL .= "<td class='day $day_name' id='form'>&nbsp; &nbsp;</td>";
               }

               if (!$leave_signal&&!$holiday_signal&&$sizeofArray==count($TimesheetData) && ($day_name!='Sun' && $day_name != 'Sat')) {
                    $calendarL .= "<td class='day $day_name' id='form' onclick='TimeSheetForm($date)'>NA</td>";
               }else if (!$leave_signal&&!$holiday_signal&&$sizeofArray==count($TimesheetData) && ($day_name=='Sun' || $day_name == 'Sat')) {
                    $calendarL .= "<td class='day $day_name' id='form'>&nbsp; &nbsp;</td>";
               }
               if (!$leave_signal&&$holiday_signal) {
                    $calendarL .= "<td class='day $day_name' id='form'>&nbsp; H &nbsp;</td>";
                    break;
               }else if($leave_signal){
                    $calendarL .= "<td class='day $day_name' id='form'>&nbsp; L &nbsp;</td>";
                    break;
               }
               $sizeofArray++;
          }

          

          // Increment counters
 
          $currentDay++;
          $dayOfWeek++;

     }
     
     

     // Complete the row of the last week in month, if necessary

     // if ($dayOfWeek != 7) { 
     
     //      $remainingDays = 7 - $dayOfWeek;
     //      $calendar .= "<td colspan='$remainingDays'>&nbsp;</td>"; 

     // }
     
     $calendar .= "</tr>";
     $calendarL .= "</tr>";

     $calendar .= $calendarL;

     $calendar .= "</table>";

     return $calendar;

}

?>
<?php
     $dateComponents = getdate();

     $month = $dateComponents['mon'];                  
     $year = $dateComponents['year'];

     echo build_calendar($month,$year,$dateArray,$this->TMSCData,$this->TimesheetData,$this->holidays,$this->holidays0,$this->leaves);
?>
<table id="calendar"><div style="padding-bottom: 50px"></div><caption><input type="button" value="Submit"></caption></table>
<div id="login-form" class="modal">
  <ul class="form-section page-section">
      <li id="cid_1" class="form-input-wide" data-type="control_head">
        <div class="form-header-group  header-large">
          <div class="header-text httal htvam">
            <h1 id="header_1" class="form-header" data-component="header">
              Project Timesheet
            </h1>
          </div>
        </div>
      </li>
      <li class="form-line" data-type="control_dropdown" id="id_14">
        <label class="form-label form-label-top form-label-auto" id="label_14" for="input_14"> Project </label>
        <div id="cid_14" class="form-input-wide" data-layout="half">
          <select class="form-dropdown" id="project" name="project" style="width:310px" data-component="dropdown" aria-labelledby="label_14">
            <option value=""> Please Select </option>
            <?php foreach ($this->allproject as $key => $value) {
                 echo "<option value='{$value['id']}'> {$value['project_name']} => {$value['task']} </option>";
            } ?>
          </select>
        </div>
      </li>
      <li class="form-line" data-type="control_textbox" id="id_19">
        <label class="form-label form-label-top form-label-auto" id="label_19" for="input_19"> Location </label>
        <div id="cid_19" class="form-input-wide" data-layout="half">
          <input type="text" id="input_19" name="location" data-type="input-textbox" class="form-textbox" style="width:310px" size="310" value="" data-component="textbox" aria-labelledby="label_19">
        </div>
      </li>
      <li class="form-line" data-type="control_textbox" id="id_21">
        <label class="form-label form-label-top form-label-auto" id="label_21" for="input_21"> Time </label>
        <div id="cid_21" class="form-input-wide" data-layout="half">
          <input type="text" id="input_21" name="time" data-type="input-textbox" class="timeEntry" style="width:310px" size="310" value="" data-component="textbox" aria-labelledby="label_21">
        </div>
      </li>
      <input type="hidden" name="date">
      <li class="form-line" data-type="control_button" id="id_2">
        <div id="cid_2" class="form-input-wide" data-layout="full">
          <div data-align="auto" class="form-buttons-wrapper form-buttons-auto   jsTest-button-wrapperField">
            <button id="saveTimeSheet" type="submit" class="form-submit-button submit-button jf-form-buttons jsTest-submitField" data-component="button" data-content="">
              Submit
            </button>
          </div>
        </div>
      </li>
      <li style="display:none">
        Should be Empty:
        <input type="text" name="website" value="">
      </li>
    </ul>
</div>
<style type="text/css">
     input[type=button] {
         background-color: #4CAF50;
         color: white;
         padding: 12px 20px;
         border: none;
         border-radius: 4px;
         cursor: pointer;
         float: right;
     }
     td.day.Sun{
          background-color: black;
          color: white;
          z-index: 100;
     }
     td.day.Sat{
          background-color: black;
          color: white;
     }
     td.day.Sun.head{
          background-color: black;
          color: white;
          z-index: 100;
     }
     td.day.Sat.head{
          background-color: black;
          color: white;
     }
     #calendar {
     width: 90%;
     /*display: grid;*/
     grid-template-columns: repeat(7, 1fr);
     }
     #calendar tr, #calendar tbody {
       grid-column: 1 / -1;
       /*display: grid;*/
       grid-template-columns: repeat(7, 1fr);
       width: 100%;
     }
     caption.month {
         padding: 70px 0px;
         width: 100%;
         background: #1abc9c;
         color: white;
         font-size: 20px;
         text-transform: uppercase;
         letter-spacing: 3px;
     }
     td.day.head {
          background: #ddd;
          letter-spacing: 1.5px;
          padding: 6px;
     }
     table { border-collapse:collapse; }
     tr.weekdays td.day {
          /*width: 100%;*/
          text-align: center;
         vertical-align: top;
         margin: 0;
         padding: 10px 0;
         /*background: #ddd;*/
     }
     td.day{
          cursor: pointer;
          text-align: center;
         padding: 10px 0;
         background: #eee;
         margin: 0;
         border: black;
     }
     ul.page-section {
         display: -ms-flexbox;
         /*display: flex;*/
         -ms-flex-align: start;
         align-items: flex-start;
         margin: 0;
         padding: 0 38px;
         list-style: none;
     }
          .form-line {
         margin-top: 12px;
         margin-bottom: 12px;
     }
     div.header-large {
         margin: 0 -38px;
         padding: 2.5em 52px;
         text-align: center;
     }
     input#input_19, input#input_21, div#select2-drop-mask {
         font: normal 12px/18px "Lucida Grande", Verdana;
         padding: 3px;
         border: 1px solid #ddd;
         width: 200px;
         min-width: 100%;
         max-width: 100%;
     }
     input[type="submit" i] {
         appearance: push-button;
         user-select: none;
         white-space: pre;
         align-items: flex-start;
         text-align: center;
         cursor: default;
         color: -internal-light-dark(black, white);
         background-color: -internal-light-dark(rgb(239, 239, 239), rgb(59, 59, 59));
         box-sizing: border-box;
         padding: 1px 6px;
         border-width: 2px;
         border-style: outset;
         border-color: -internal-light-dark(rgb(118, 118, 118), rgb(133, 133, 133));
         border-image: initial;
     }
     td#form {
         padding: 12px 5px;
     }
</style>
<script type="text/javascript">
     function TimeSheetForm(elstr) {
          $("input[name=date]").val(elstr);
            $('#login-form').modal({
              fadeDuration: 250
            });
         }
     $(document).ready(function(){
     $('.breadcrumbs').append("<span class='arrows'>&rsaquo;</span><a href='<?php echo BASE_URL; ?>timemanagement'>Time Sheet</a>");
     $('.timeEntry').timeEntry({show24Hours:true,minTime: new Date(0, 0, 0, 4, 30, 0),maxTime: new Date(0, 0, 0, 8, 30, 0)});
      $('#saveTimeSheet').click(function(){
          $.modal.close();
          var project = $("#project option:selected").val();
          var location = $("input[name=location]").val();
          var time = $("input[name=time]").val();
          var date = $("input[name=date]").val();
          $("#project option:selected").removeAttr("selected"); 
          $("input[name=location]").val("");
          $("input[name=time]").val("");
          var data = {project: project, location: location, time: time, date: date};
          $.post('<?php echo $this->baseUrl("index.php/timemanagement/index/week");?>', data, function(returnedData) {
              console.log(returnedData);
              if(returnedData!=null){
                    window.location.reload(true);
              }
          });
      })
   });
</script>
<!-- jQuery Modal -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />