<?php

function build_calendar($month,$year,$dateArray,$TMSCData,$TimesheetData,$holidays,$holidays0,$leaves,$allproject,$url) {

     // Create array containing abbreviations of days of week.
     // $daysOfWeek = array('S','M','T','W','T','F','S','S','M','T','W','T','F','S','S','M','T','W','T','F','S','S','M','T','W','T','F','S','S','M','T','W','T','F','S');

     // What is the first day of the month in question?
     $firstDayOfMonth = mktime(0,0,0,$month,1,$year);

     // How many days does this month contain?
     $numberDays = date('t',$firstDayOfMonth);

     // Retrieve some information about the first day of the
     // month in question.
     $dateComponents = getdate($firstDayOfMonth);

     // What is the name of the month in question?
     $monthName = $dateComponents['month'];
     $monthNameL = date("F", strtotime($TMSCData[0]['form']));
     $yearNameL = date("Y", strtotime($TMSCData[0]['form']));

     // What is the index value (0-6) of the first day of the
     // month in question.
     $dayOfWeek = $dateComponents['wday'];

     // Create the table tag opener and day headers
     $calendar = "<form method='POST' id='tmsheetform' style='overflow: auto;'><table id='calendar'>";
     $calendar .= "<caption class='month'>$monthNameL $yearNameL Actual Time, ";
     $calendar .= "$monthName $year Actual Time, ";
     $calendar .= "$monthName $year Estimated Time</caption>";
     $calendar .= "<tr>";

     // Create the calendar headers

     // foreach($daysOfWeek as $day) {
     //      $calendar .= "<th class='header'>$day</th>";
     // } 

     // Create the rest of the calendar

     // Initiate the day counter, starting with the 1st.

     $currentDay = 1;

     $calendar .= "</tr><tr class = 'weekdays'><td class='day head'>Project and Code</td><td class='day head'>Location</td>";

     // The variable $dayOfWeek is used to
     // ensure that the calendar
     // display consists of exactly 7 columns.

     // if ($dayOfWeek > 0) { 
     //      $calendar .= "<td colspan='$dayOfWeek'>&nbsp;</td>"; 
     // }
     
     $month = str_pad($month, 2, "0", STR_PAD_LEFT);

     $currentDayL = date("d", strtotime($TMSCData[0]['form']));
     $numberDaysL = date("t", strtotime($TMSCData[0]['form']));
     $dayOfWeekL = 0;
     $monthL = date("m", strtotime($TMSCData[0]['form']));
     $yearL = date("Y", strtotime($TMSCData[0]['form']));
     $calendarL = "<tr><td>Project and Code</td><td>Location</td>";

     if(count($holidays)>0){
          $holiday_names = explode(',', $holidays[0]['holiday_names']);
          $holiday_dates = explode(',', $holidays[0]['holiday_dates']);
     }
     if (count($holidays0)>0) {
          $holiday_names0 = explode(',', $holidays0[0]['holiday_names']);
          $holiday_dates0 = explode(',', $holidays0[0]['holiday_dates']);
     }

     foreach ($allproject as $key => $value) {
          ${'calendar'.$key}="<tr><td class='day'>
               <select class='form-dropdown' id='project' name='project[]' style='width:206px' data-component='dropdown' aria-labelledby='label_14'>
                 <option value=''> Please Select </option>
                 ";
                 foreach ($allproject as $index => $valv) {
                      ${'calendar'.$key}.= "<option value='{$valv['id']}'> {$valv['project_name']} => {$valv['task']} </option>";
                 }
                 ${'calendar'.$key}.="
               </select>
          </td><td class='day'><input type='text' id='fname' name='location[]'></td>";
     }
     // var_dump($holiday_names0);
     // die();

     // var_dump(date("F", strtotime($TMSCData[0]['form'])));
     $totalTablesize = 0;
     $rowarray = [];
     $workingDays = 0;

     while ($currentDayL <= $numberDaysL) {

          // Seventh column (Saturday) reached. Start a new row.

          // if ($dayOfWeek == 30) {

          //      $dayOfWeek = 0;
          //      $calendar .= "</tr><tr>";

          // }
          
          $currentDayRel = str_pad($currentDayL, 2, "0", STR_PAD_LEFT);
          
          $date = "$yearL-$monthL-$currentDayRel";
          $get_name = date('l', strtotime($date)); //get week day
          $day_name = substr($get_name, 0, 3); // Trim day name to 3 chars

          $calendar .= "<td class='day $day_name head' rel='$date'><b>$day_name</b> <div>$currentDayL</div></td>";

          $leave_signal = false;
          $leave_signal_half = false;
          foreach ($leaves as $key => $value) {
               if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavestatus']=='Approved'&&$value['appliedleavescount']=='0.5')
               {
                    $leave_signal_half=true;
                    break;
               }elseif(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavestatus']=='Approved'){
                    $leave_signal=true;
                    break;
               }
          }

          $holiday_signal = false;
          foreach ($holiday_dates as $key => $value) {
               if($value==$date){
                    $holiday_signal=true;
               }
          }

          foreach ($allproject as $key => $value) {
               if(($day_name=='Sun' || $day_name == 'Sat')){
                    ${'calendar'.$key}.="<td class='day $day_name' id='form'></td>";
               }else if($leave_signal_half){
                ${'calendar'.$key}.="<td class='day $day_name' id='form'><input type='text' id='fname' name='time[]' maxlength='4' size='4' class='halfleaveTimeEntry'><input type='hidden' name='date[]' value='$date'></td>";
               }else if($leave_signal){
                ${'calendar'.$key}.="<td class='day $day_name' id='form'>Leave day</td>";
               }else if($holiday_signal){
                ${'calendar'.$key}.="<td class='day $day_name' id='form'>holiday</td>";
               }elseif ($day_name=='Fri') {
                 ${'calendar'.$key}.="<td class='day $day_name' id='form'><input type='text' id='fname' name='time[]' maxlength='4' size='4' class='friTimeEntry'><input type='hidden' name='date[]' value='$date'></td>";
               }else{
               ${'calendar'.$key}.="<td class='day $day_name' id='form'><input type='text' id='fname' name='time[]' maxlength='4' size='4' class='timeEntry'><input type='hidden' name='date[]' value='$date'></td>";
               }
          }

          if(($day_name=='Sun' || $day_name == 'Sat')){
               array_push($rowarray,"<td class='day $day_name' id='form'></td>");
          }elseif($leave_signal_half){
            array_push($rowarray,"<td class='day $day_name' id='form'><input type='text' id='fname' name='time[]' maxlength='4' size='4' class='halfleaveTimeEntry'><input type='hidden' class='dateclass' name='date[]' value='$date'></td>");
               $workingDays++;
          }elseif($leave_signal){
            array_push($rowarray,"<td class='day $day_name' id='form'>Leave Day</td>");
          }elseif($holiday_signal){
            array_push($rowarray,"<td class='day $day_name' id='form'>Holiday</td>");
          }elseif ($day_name=='Fri') {
            array_push($rowarray,"<td class='day $day_name' id='form'><input type='text' id='fname' name='time[]' maxlength='4' size='4' class='friTimeEntry'><input type='hidden' class='dateclass' name='date[]' value='$date'></td>");
               $workingDays++;
          }else{
               array_push($rowarray,"<td class='day $day_name' id='form'><input type='text' id='fname' name='time[]' maxlength='4' size='4' class='timeEntry'><input type='hidden' class='dateclass' name='date[]' value='$date'></td>");
               $workingDays++;
          }

          $date = "&quot;$yearL-$monthL-$currentDayRel&quot;";

          $sizeofArray = 0;
          foreach ($TimesheetData as $key => $value) {
               $d=strtotime($value['date']);
               $vd = date("Y-m-d", $d);
               if (!$leave_signal&&!$holiday_signal&&"&quot;".$vd."&quot;"==$date && $day_name!='Sun' && $day_name != 'Sat') {
                    $calendarL .= "<td class='day $day_name' id='form'>{$value['duration']}</td>";
                    break;
               }else if (!$leave_signal&&!$holiday_signal&&"&quot;".$vd."&quot;"==$date && ($day_name=='Sun' || $day_name == 'Sat')) {
                    $calendarL .= "<td class='day $day_name' id='form' onclick='TimeSheetForm($date)'>&nbsp; &nbsp;</td>";
               }

               if (!$leave_signal&&!$holiday_signal&&$sizeofArray==count($TimesheetData) && ($day_name!='Sun' && $day_name != 'Sat')) {
                    $calendarL .= "<td class='day $day_name' id='form' onclick='TimeSheetForm($date)'>NA</td>";
               }else if (!$leave_signal&&!$holiday_signal&&$sizeofArray==count($TimesheetData) && ($day_name=='Sun' || $day_name == 'Sat')) {
                    $calendarL .= "<td class='day $day_name' id='form'>&nbsp; &nbsp;</td>";
               }
               if(!$leave_signal&&$holiday_signal){
                    $calendarL .= "<td class='day $day_name' id='form'>&nbsp; H &nbsp;</td>";
                    break;
               }else if($leave_signal){
                    $calendarL .= "<td class='day $day_name' id='form'>&nbsp; L &nbsp;</td>";
                    break;
               }
               $sizeofArray++;
               
          }

          // Increment counters
 
          $currentDayL++;
          $dayOfWeekL++;
          $totalTablesize++;

     }


     while ($currentDay <= $numberDays) {

          // Seventh column (Saturday) reached. Start a new row.

          // if ($dayOfWeek == 30) {

          //      $dayOfWeek = 0;
          //      $calendar .= "</tr><tr>";

          // }
          
          $currentDayRel = str_pad($currentDay, 2, "0", STR_PAD_LEFT);
          
          $date = "$year-$month-$currentDayRel";
          $get_name = date('l', strtotime($date)); //get week day
          $day_name = substr($get_name, 0, 3); // Trim day name to 3 chars

          $calendar .= "<td class='day $day_name head' rel='$date'><b>$day_name</b> <div>$currentDay</div></td>";
          // $calendarL .= "<td class='day $day_name' rel='$date' id='form'>00:00</td>";

          $leave_signal = false;
          $leave_signal_half = false;
          foreach ($leaves as $key => $value) {
               if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavestatus']=='Approved'&&$value['appliedleavescount']=='0.5')
               {
                    $leave_signal_half=true;
                    break;
               }elseif (($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavestatus']=='Approved') {
                    $leave_signal=true;
                    break;
               }
          }
          $holiday_signal = false;
          foreach ($holiday_dates0 as $key => $value) {
               if($value==$date){
                    $holiday_signal=true;
               }
          }

          foreach ($allproject as $key => $value) {
               if(($day_name=='Sun' || $day_name == 'Sat')){
                    ${'calendar'.$key}.="<td class='day $day_name' id='form'></td>";
               }elseif($leave_signal_half){
                  ${'calendar'.$key}.="<td class='day $day_name' id='form'><div style='font-size: xx-small;'>half day leave</div><input type='text' id='fname' name='time[]' maxlength='4' size='4' class='halfleaveTimeEntry'><input type='hidden' name='date[]' value='$date'></td></td>";
               }elseif($leave_signal){
                  ${'calendar'.$key}.="<td class='day $day_name' id='form'>Leave day</td>";
               }elseif($holiday_signal){
                  ${'calendar'.$key}.="<td class='day $day_name' id='form'>Holiday</td>";
               }elseif ($day_name=='Fri') {
                 ${'calendar'.$key}.="<td class='day $day_name' id='form'><input type='text' id='fname' name='time[]' maxlength='4' size='4' class='friTimeEntry'><input type='hidden' name='date[]' value='$date'></td></td>";
               }else{
               ${'calendar'.$key}.="<td class='day $day_name' id='form'><input type='text' id='fname' name='time[]' maxlength='4' size='4' class='timeEntry'><input type='hidden' name='date[]' value='$date'></td></td>";
               }
          }

          if(($day_name=='Sun' || $day_name == 'Sat')){
               array_push($rowarray,"<td class='day $day_name' id='form'></td>");
          }elseif($leave_signal_half){
              array_push($rowarray,"<td class='day $day_name' id='form'><div style='font-size: xx-small;'>half day leave</div><input type='text' id='fname' name='time[]' maxlength='4' size='4' class='halfleaveTimeEntry'><input type='hidden' name='date[]' value='$date'></td>");
               $workingDays++;
          }elseif($leave_signal){
              array_push($rowarray,"<td class='day $day_name' id='form'>Leave Day</td>");
          }elseif($holiday_signal){
              array_push($rowarray,"<td class='day $day_name' id='form'>Holiday</td>");
          }elseif($day_name=='Fri') {
            array_push($rowarray,"<td class='day $day_name' id='form'><input type='text' id='fname' name='time[]' maxlength='4' size='4' class='friTimeEntry'><input type='hidden' name='date[]' value='$date'></td>");
               $workingDays++;
          }else{
               array_push($rowarray,"<td class='day $day_name' id='form'><input type='text' id='fname' name='time[]' maxlength='4' size='4' class='timeEntry'><input type='hidden' name='date[]' value='$date'></td>");
               $workingDays++;
          }

          $date = "&quot;$year-$month-$currentDayRel&quot;";
          $sizeofArray = 1;
          foreach ($TimesheetData as $key => $value) {
               $d=strtotime($value['date']);
               $vd = date("Y-m-d", $d);
               if (!$leave_signal&&!$holiday_signal&&"&quot;".$vd."&quot;"==$date && ($day_name!='Sun' || $day_name != 'Sat')) {
                    $calendarL .= "<td class='day $day_name' id='form' onclick='TimeSheetForm($date)'>{$value['duration']}</td>";
                    break;
               }else if (!$leave_signal&&!$holiday_signal&&"&quot;".$vd."&quot;"==$date && ($day_name=='Sun' || $day_name == 'Sat')) {
                    $calendarL .= "<td class='day $day_name' id='form'>&nbsp; &nbsp;</td>";
               }

               if (!$leave_signal&&!$holiday_signal&&$sizeofArray==count($TimesheetData) && ($day_name!='Sun' && $day_name != 'Sat')) {
                    $calendarL .= "<td class='day $day_name' id='form' onclick='TimeSheetForm($date)'>NA</td>";
               }else if (!$leave_signal&&!$holiday_signal&&$sizeofArray==count($TimesheetData) && ($day_name=='Sun' || $day_name == 'Sat')) {
                    $calendarL .= "<td class='day $day_name' id='form'>&nbsp; &nbsp;</td>";
               }
               if (!$leave_signal&&$holiday_signal) {
                    $calendarL .= "<td class='day $day_name' id='form'>&nbsp; H &nbsp;</td>";
                    break;
               }else if($leave_signal){
                    $calendarL .= "<td class='day $day_name' id='form'>&nbsp; L &nbsp;</td>";
                    break;
               }
               $sizeofArray++;
               
          }

          

          // Increment counters
 
          $currentDay++;
          $dayOfWeek++;
          $totalTablesize++;

     }
     
     

     // Complete the row of the last week in month, if necessary

     // if ($dayOfWeek != 7) { 
     
     //      $remainingDays = 7 - $dayOfWeek;
     //      $calendar .= "<td colspan='$remainingDays'>&nbsp;</td>"; 

     // }
     
     $calendar .= "<td></td></tr>";
     $calendarL .= "</tr>";

     // $calendar .= $calendarL;

     // foreach ($allproject as $key => $value) {
               $calendar0.="</tr>";
               $calendar .= $calendar0;

               $holidaycal = "<table>";
               for ($i=0; $i < count($holiday_dates); $i++) { 
                 $holidaycal .= "<tr><td>".$holiday_dates[$i]."</td><td> &nbsp; </td><td>".$holiday_names[$i]."</td></tr>";
               }
               for ($i=0; $i < count($holiday_dates0); $i++) { 
                 $holidaycal .= "<tr><td>".$holiday_dates0[$i]."</td><td> &nbsp; </td><td>".$holiday_names0[$i]."</td></tr>";
               }
          // }
               $json = json_encode($rowarray);
     $calendar .= "</table><div id='tableSize' value='".htmlentities($json, ENT_QUOTES, 'UTF-8')."'><div id='workingDays' value='$workingDays'></div><div>";
     $calendar .= $holidaycal."</table>";

     return $calendar;

}

?>
<?php
     $dateComponents = getdate();

     $month = $dateComponents['mon'];                  
     $year = $dateComponents['year'];

     if($this->TMstatus[0]['status']=="For Approval"){
        echo "<br><div>Your timesheet is already sent !</div>";
     }else if($this->TMstatus[0]['status']=="Approved"){
          echo "<br><div>Your timesheet is already approved !</div>";
     }else {
          echo build_calendar($month,$year,$dateArray,$this->TMSCData,$this->TimesheetData,$this->holidays,$this->holidays0,$this->leaves,$this->allproject,$this->baseUrl("index.php/timemanagement/index/week"));
     }
?>
<?php 
     if($this->TMstatus[0]['status']=="For Approval"){
        
     }else if($this->TMstatus[0]['status']=="Approved"){
          
     }else {
          ?>
          <table id="calendar"><div style="padding-bottom: 50px"></div><caption>
         <label>Comment:</label>
          <textarea name="comment" rows="4" cols="50">
       </textarea>
          <input id="submit" type="submit" name="submit_row" value="Submit For Approval" style="float: right; background-color: #4CAF50;
         color: white;
         padding: 12px 20px;
         border: none;
         border-radius: 4px;
         cursor: pointer;">
          <input type="button" onclick="add_row();" value="Add Project" style="float: left;">
     </caption></table></form>
          <?php
     }
 ?>
<style type="text/css">
     input[type=button] {
         background-color: #4CAF50;
         color: white;
         padding: 12px 20px;
         border: none;
         border-radius: 4px;
         cursor: pointer;
         float: right;
     }
     td.day.Sun{
          background-color: black;
          color: white;
          z-index: 100;
     }
     td.day.Sat{
          background-color: black;
          color: white;
     }
     td.day.Sun.head{
          background-color: black;
          color: white;
          z-index: 100;
     }
     td.day.Sat.head{
          background-color: black;
          color: white;
     }
     #calendar {
     width: 100%;
     /*display: grid;*/
     grid-template-columns: repeat(7, 1fr);
     }
     #calendar tr, #calendar tbody {
       grid-column: 1 / -1;
       /*display: grid;*/
       grid-template-columns: repeat(7, 1fr);
       width: 100%;
     }
     caption.month {
         padding: 20px 0px;
         width: 100%;
         background: #82a81c;
         color: white;
         font-size: 20px;
         text-transform: uppercase;
         letter-spacing: 3px;
     }
     td.day.head {
          background: #ddd;
          letter-spacing: 1.5px;
          padding: 6px;
     }
     table { border-collapse:collapse; }
     tr.weekdays td.day {
          /*width: 100%;*/
          text-align: center;
         vertical-align: top;
         margin: 0;
         padding: 10px 0;
         /*background: #ddd;*/
     }
     td.day{
          cursor: pointer;
          text-align: center;
         padding: 10px 0;
         background: #eee;
         margin: 0;
         border: black;
     }
     ul.page-section {
         display: -ms-flexbox;
         /*display: flex;*/
         -ms-flex-align: start;
         align-items: flex-start;
         margin: 0;
         padding: 0 38px;
         list-style: none;
     }
          .form-line {
         margin-top: 12px;
         margin-bottom: 12px;
     }
     div.header-large {
         margin: 0 -38px;
         padding: 2.5em 52px;
         text-align: center;
     }
     input#input_19, input#input_21, div#select2-drop-mask {
         font: normal 12px/18px "Lucida Grande", Verdana;
         padding: 3px;
         border: 1px solid #ddd;
         width: 200px;
         min-width: 100%;
         max-width: 100%;
     }
     input[type="submit" i] {
         appearance: push-button;
         user-select: none;
         white-space: pre;
         align-items: flex-start;
         text-align: center;
         cursor: default;
         color: -internal-light-dark(black, white);
         background-color: -internal-light-dark(rgb(239, 239, 239), rgb(59, 59, 59));
         box-sizing: border-box;
         padding: 1px 6px;
         border-width: 2px;
         border-style: outset;
         border-color: -internal-light-dark(rgb(118, 118, 118), rgb(133, 133, 133));
         border-image: initial;
     }
     td#form {
         padding: 12px 5px;
     }

</style>
<script type="text/javascript">
     function add_row()
     {
      var x = document.getElementById("tableSize").getAttribute("value");
      x=JSON.parse(x);
      $rowno=$("#calendar tr").length;
      $rowno=$rowno+1;
      var str = "<tr id='row"+$rowno+"'><td class='day'><select class='form-dropdown' id='project' name='project[]' style='width:206px' data-component='dropdown' aria-labelledby='label_14'>"+
                 "<option value=''> Please Select </option>"+
                 <?php 
                 foreach ($this->allproject as $index => $valv) {
                      echo "\"<option value='{$valv['id']}'> {$valv['project_name']} => {$valv['task']} </option>\"+";
                 }
                  ?>
               "</select></td><td class='day'><input type='text' id=' location' name='location[]'></td>";
               for (var i = 0; i < x.length; i++) {
                    str+=x[i];
               }
               str+="<td><input type='button' value='DELETE' onclick=delete_row('row"+$rowno+"')></td></tr>";
               $("#calendar tr:last").after(str);
               $('.timeEntry').timeEntry({show24Hours:true,minTime: new Date(0, 0, 0, 0, 0, 0),maxTime: new Date(0, 0, 0, 8, 30, 0)});
               $('.friTimeEntry').timeEntry({show24Hours:true,minTime: new Date(0, 0, 0, 0, 0, 0),maxTime: new Date(0, 0, 0, 4, 30, 0)});
               $('.halfleaveTimeEntry').timeEntry({show24Hours:true,minTime: new Date(0, 0, 0, 0, 0, 0),maxTime: new Date(0, 0, 0, 4, 30, 0)});
     }
     function delete_row(rowno)
     {
      $('#'+rowno).remove();
     }
     function TimeSheetForm(elstr) {
          $("input[name=date]").val(elstr);
            $('#login-form').modal({
              fadeDuration: 250
            });
         }
     $(document).ready(function(){
     $("form").submit(function(e){
          e.preventDefault();
         // alert("Submitted");
         var wd = document.getElementById("workingDays").getAttribute("value");
         var v = $('#tmsheetform').serializeArray();
         var l = [];
         var t = [];
         var d = [];
         var p = [];
         var c = [];
         for (var i = 0; i < v.length; i++) {
             // console.log(v[i]['name']);
             // console.log(v[i]['value']);
             if (v[i]['name']=='project[]') 
             {
              p.push({
                'name':'project_id',
                'value':v[i]['value']
                });
             }
             if (v[i]['name']=='location[]') 
             {
              l.push({
                'name':'location',
                'value':v[i]['value']
                });
             }
             if (v[i]['name']=='time[]') 
             {
              t.push({
                'name':'time',
                'value':v[i]['value']
                });
             }
             if (v[i]['name']=='date[]') 
             {
              d.push({
                'name':'date',
                'value':v[i]['value']
                });
             }
             if(v[i]['name']=='comment')
             {
              c.push({
                'name':'comment',
                'value':v[i]['value']
              })
             }
         }
         // var vals = $(".dateclass").map(function(){ return this.value}).get();
         // console.log(p);
         
          function timeToDecimal(t) {
              var arr = t.split(':');
              var dec = parseInt((arr[1]/6)*10, 10);
              return parseFloat(parseInt(arr[0], 10) + '.' + (dec<10?'0':'') + dec);
          }
          var validation = true;
          var halftime = "04:30";
          var fulltime = "08:30";
          var halfDay = new Date("01/01/2000 "+halftime);
          var fullDay = new Date("01/01/2000 "+fulltime);
         for (var i = p.length - 1; i >= 0; i--) {
              if(p[i]['value']==""){
               alert("Please select a project for Your Timesheet");
               validation = false;
              }
         }
         var lastdateArray = 0;
         var timeArry = [];

         for (var i = 0; i<p.length;i++) {
               // var maketime = new Date("01/01/2000 "+t[i]['value']);
               // if(t[i]['value']!=''&&maketime>fullDay){
               //      alert('Your Timesheet is more than a day total in '+d[i]['value']);
               // }
               const counter = parseInt(wd)*(i+1);
               if (t.length>wd) {
                    var index = 0;
                    for (var j=lastdateArray; j < counter; j++) {
                         lastdateArray=j+1;
                         var maketime = 0;
                         if (t[j]['value']!='') {
                              maketime = t[j]['value'];
                         }else{
                              maketime = '00:00';
                         }
                         var date = d[j]['value'];
                         timeArry[index]=timeArry[index]!=null?(timeArry[index])+timeToDecimal(maketime):timeToDecimal(maketime);
                         index++;
                    }
               }
               // console.log(timeArry);
         }
         for (var i = 0; i < timeArry.length; i++) {
          var da = new Date(d[i]['value']);
          var dayName = da.toString().split(' ')[0];
              if (dayName=='Fri') {
               if (timeArry[i]>4.5) {
                    alert('Please review Your time in '+d[i]["value"]+' its more than a day allowed !');
                    validation = false;
               }
              }else if(timeArry[i]>8.5) {
                    alert('Please review Your time in '+d[i]["value"]+' its more than a day allowed !');
                    validation = false;
              }
         }
         // alert(c);
         // if (true) {}
         var data = {project: p, location: l, time: t, date: d, workingDays: wd, comment: c};
         if (validation) {
          $.post('<?php echo $this->baseUrl("index.php/timemanagement/index/week");?>', data, function(returnedData) {
              console.log(returnedData);
              if(returnedData!=null){
                    console.log(returnedData);
                    alert(returnedData);
                    window.location.reload(true);
                    // console.log(returnedData);
                    // alert(returnedData);
              }
            });
         }
       });
     $('.breadcrumbs').append("<span class='arrows'>&rsaquo;</span><a href='<?php echo BASE_URL; ?>timemanagement'>Time Sheet</a>");
     $('.timeEntry').timeEntry({show24Hours:true,minTime: new Date(0, 0, 0, 0, 0, 0),maxTime: new Date(0, 0, 0, 8, 30, 0)});
     $('.friTimeEntry').timeEntry({show24Hours:true,minTime: new Date(0, 0, 0, 0, 0, 0),maxTime: new Date(0, 0, 0, 4, 30, 0)});
     $('.halfleaveTimeEntry').timeEntry({show24Hours:true,minTime: new Date(0, 0, 0, 0, 0, 0),maxTime: new Date(0, 0, 0, 4, 30, 0)});
      $('#saveTimeSheet').click(function(){
          $.modal.close();
          var project = $("#project option:selected").val();
          var location = $("input[name=location]").val();
          var time = $("input[name=time]").val();
          var date = $("input[name=date]").val();
          $("#project option:selected").removeAttr("selected"); 
          $("input[name=location]").val("");
          $("input[name=time]").val("");
          var data = {project: project, location: location, time: time, date: date};
          $.post('<?php echo $this->baseUrl("index.php/timemanagement/index/week");?>', data, function(returnedData) {
              // console.log(returnedData);
              if(returnedData!=null){
                    window.location.reload(true);
              }
          });
      })
   });
</script>
<!-- jQuery Modal -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />