<?php 
function clockalize($in){

    $h = intval($in);
    $m = round((((($in - $h) / 100.0) * 60.0) * 100), 0);
    if ($m == 60)
    {
        $h++;
        $m = 0;
    }
    $retval = sprintf("%02d:%02d", $h, $m);
    return $retval;
}
function decimalSum($val0,$val1){
  return $val0+$val1;
}
function decimalHours($time)
{
    $hms = explode(":", $time);
    return number_format((float)($hms[0] + ($hms[1]/60) + ($hms[2]/3600)), 2, '.', '');
}
function build_calendar_Holiday_View(){
	$calendar = "<tr class=xl727473 height=19 style='mso-height-source:userset;height:14.25pt'>
  <td colspan=2 height=19 class=xl2607473 style='height:14.25pt'>Total LOE<span
  style='mso-spacerun:yes'>  </span>%age</td>
 ";
 $var=1;
 while ($var <= 38) {
 	$calendar .= "<td class=xl727473></td>";
 	$var++;
 }
 $calendar .= "</tr>";
	return $calendar;
}
function build_calendar($month,$year,$dateArray,$TMSCData,$sentTimesSheets,$leaveTypes,$empHolidays) {
	$lastDateOfMonth = date("Y-m-t", strtotime($TMSCData[0]['form']));
	$lastDateOfMonthTo = date("Y-m-t", strtotime($TMSCData[0]['to']));
	$date_diff = date_diff(date_create($TMSCData[0]['form']),date_create($lastDateOfMonth));
	$date_diffTo = date_diff(date_create($lastDateOfMonthTo),date_create($TMSCData[0]['to']));
	$date_diffTotal = date_diff(date_create($TMSCData[0]['form']),date_create($TMSCData[0]['to']));
	$Total = (strtotime($TMSCData[0]['form']) - strtotime($TMSCData[0]['to']))/60/60/24 * (-1);
	$DateFrom = (int)$date_diff->format('%d')+1;
	$DateTo = (int)$date_diffTo->format('%d')+1;
	$Total = $Total - $DateFrom;

	// var_dump($Total);
	// var_dump($DateFrom);
	// var_dump($DateTo);
	// var_dump($lastDateOfMonth);
	// var_dump($lastDateOfMonthTo);
	// var_dump($leaveTypes);
	// for ($x = 0; $x < count($leaveTypes); $x++) {
	// 	var_dump($leaveTypes[$x]['leavetype']);
	// }
	// die();
     // Create array containing abbreviations of days of week.
     $daysOfWeek = array('S','M','T','W','T','F','S','S','M','T','W','T','F','S','S','M','T','W','T','F','S','S','M','T','W','T','F','S','S','M','T','W','T','F','S');

     // What is the first day of the month in question?
     $firstDayOfMonth = mktime(0,0,0,$month,1,$year);

     // How many days does this month contain?
     $numberDays = date('t',$firstDayOfMonth);

     // Retrieve some information about the first day of the
     // month in question.
     $dateComponents = getdate($firstDayOfMonth);

     // What is the name of the month in question?
     $monthName = $dateComponents['month'];
     $monthNameL = date("F", strtotime($TMSCData[0]['form']));
     $yearNameL = date("Y", strtotime($TMSCData[0]['form']));

     // What is the index value (0-6) of the first day of the
     // month in question.
     $dayOfWeek = $dateComponents['wday'];

     // Create the table tag opener and day headers

     // $calendar = "<table class='calendar'>";
     // $calendar .= "<caption>$monthNameL $yearNameL Actual Time ";
     $calendar .= "<tr class=xl867473 height=35 style='mso-height-source:userset;height:26.25pt'>
  <td colspan=3 rowspan=2 height=61 class=xl2737473 style='border-bottom:1.0pt solid black;
  height:45.75pt'>Description</td>
  <td colspan=".(int)$DateFrom." class=xl2797473 width=222 style='border-right:1.0pt solid black;
  width:168pt'>$monthNameL $yearNameL Actual Time</td>
  <td colspan=".$Total." class=xl2827473 style='border-right:1.0pt solid black;
  border-left:none'>$monthName $year<span style='mso-spacerun:yes'>  </span>Actual
  Time</td>
  <td colspan=".$DateTo." class=xl2857473 style='border-right:1.0pt solid black;
  border-left:none'>$monthName $year <br>
    Estimated Time</td>
  <td rowspan=3 class=xl2707473 width=43 style='width:32pt'>Total Hours</td>
 </tr>";
     // $calendar .= "$monthName $year Actual Time ";
     // $calendar .= "$monthName $year Estimated Time</caption>";
     $calendar .= "<tr class=xl877473 height=26 style='mso-height-source:userset;height:19.5pt'>";

     // Create the calendar headers

     // foreach($daysOfWeek as $day) {
     //      $calendar .= "<th class='header'>$day</th>";
     // } 

     // Create the rest of the calendar

     // Initiate the day counter, starting with the 1st.

     $currentDay = 1;

     // $calendar .= "</tr><tr>";

     // The variable $dayOfWeek is used to
     // ensure that the calendar
     // display consists of exactly 7 columns.

     // if ($dayOfWeek > 0) { 
     //      $calendar .= "<td colspan='$dayOfWeek'>&nbsp;</td>"; 
     // }
     
     $month = str_pad($month, 2, "0", STR_PAD_LEFT);

     $currentDayL = date("d", strtotime($TMSCData[0]['form']));
     $numberDaysL = date("t", strtotime($TMSCData[0]['form']));
     $dayOfWeekL = 0;
     $monthL = date("m", strtotime($TMSCData[0]['form']));
     $yearL = date("Y", strtotime($TMSCData[0]['form']));
     $project = '';
     $task = '';
     foreach ($sentTimesSheets as $key => $value) {
     	$project = $value['project_name']!=null?$value['project_name']:$project;
     	$task = $value['task']!=null?$value['task']:$task;
     }
     // var_dump($sentTimesSheets);
     $calendarP = "";
     $init = 0;
     foreach ($sentTimesSheets as $key => $value) {
      ${'calendar'.$key}.="<td height=31 class=xl1357473 style='height:23.25pt'><small> ".$value[$init]['project_name']."</small></td>
  <td class=xl1057473 style='font-size:8px;' style='border-left:none'><small>".$value[$init]['task']."</small></td><td class=xl1057473 style='border-left:none'><small>".$value[$init]['location']."</small></td>";
      $init++;
     }

     $calendarL = "<td height=31 class=xl1357473 style='height:23.25pt'>$project</td>
  <td class=xl1057473 style='border-left:none'>$task</td><td class=xl1057473 style='border-left:none'>$task</td>";
  	$calendarS = "";

  	$calendarSpace .= "<tr height=31 style='mso-height-source:userset;height:23.25pt'><td height=31 class=xl1457473 style='height:23.25pt;border-top:none'>&nbsp;</td>
  <td class=xl1057473 style='border-left:none'><span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl1037473 style='border-top:none;border-left:none'>&nbsp;</td>";

  $calendarLeaveHeader .= "<tr height=31 style='mso-height-source:userset;height:23.25pt'><td height=31 class=xl1097473 style='height:23.25pt;border-top:none'>LEAVE</td>
  <td class=xl1057473 style='border-left:none'><span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl1037473 style='border-top:none;border-left:none'>&nbsp;</td>";

  $calendarSickleave .= "<td height=33 class=xl687473 style='height:24.75pt'>Sick leave</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>";

  $calendarMaternityLeave .= "<td height=33 class=xl687473 style='height:24.75pt'>Maternity leave</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>";

  $calendarPaternityLeave .= "<td height=33 class=xl687473 style='height:24.75pt'>Paternity Leave</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>";

  $calendarFamilyLeave .= "<td height=33 class=xl687473 style='height:24.75pt'>Family Leave</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>";

  $calendarPublicHoliday .= "<td height=33 class=xl687473 style='height:24.75pt'>Public Holiday</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>";

  $calendarStudyleave .= "<td height=33 class=xl687473 style='height:24.75pt'>Study leave</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>";

  $calendarAnnualLeave .= "<td height=33 class=xl687473 style='height:24.75pt'>Annual Leave</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>";

  $calendarFloatingHoliday .= "<td height=33 class=xl687473 style='height:24.75pt'>Floating Holiday</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>";

  $calendarOther .= "<td height=33 class=xl687473 style='height:24.75pt'>Other</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>
  <td class=xl1057473 style='border-left:none'>&nbsp;</td>";

  $calendarSubTotalTime .= "<tr height=34 style='mso-height-source:userset;height:25.5pt'>
  <td height=34 class=xl1077473 width=99 style='height:25.5pt;width:74pt'>Sub
  Total <br>
    Working days</td>
  <td class=xl1087473 style='border-left:none'><span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl1087473 style='border-left:none'>&nbsp;</td>";

  $calendarSubTotalLeave = "<td height=29 class=xl1177473 style='height:21.75pt'>Sub Total <br>
    Leaves</td>
  <td class=xl1087473 style='border-left:none'>&nbsp;</td>
  <td class=xl1087473 style='border-left:none'>&nbsp;</td>";

  $caledarGrandTotal = "<tr height=29 style='mso-height-source:userset;height:21.75pt'>
  <td height=29 class=xl1187473 style='height:21.75pt;border-top:none'>Grand
  Total</td>
  <td class=xl1197473 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1197473 style='border-top:none;border-left:none'>&nbsp;</td>";
     // $calendarL = "<tr>";
     // var_dump(date("F", strtotime($TMSCData[0]['form'])));
  $holiday_names = explode(',', $empHolidays['holiday_names']);
  $holiday_dates = explode(',', $empHolidays['holiday_dates']);
  // var_dump($holiday_dates);
  // die();
    foreach ($sentTimesSheets as $key => $value) {
      ${'totalTimeRow'.$key}=0;
      foreach ($value as $ke => $val) {
        ${'totalTimeColumn'.$ke}=0;
        ${'totalTimeColumnwithLeave'.$ke}=0;
      }
    }

    $calendarSubTotalTimeSum = 0;
    $calendarSubTotalLeaveSum = 0;

    $cdl=$currentDayL;
    $ndl =$numberDaysL;
    $cd=$currentDay;
    $nd=$numberDays;

    while ($cdl <= $ndl) {
      ${'totalLeaveColumn'.$cdl}=0;
      $cdl++;
    }
    while ($cd <= $nd) {
      ${'totalLeaveColumn'.$cd}=0;
      $cd++;
    }

    $calendarSickleaveRow=0;
    $calendarMaternityLeaveRow=0;
    $calendarPaternityLeaveRow=0;
    $calendarFamilyLeaveRow=0;
    $calendarPublicHolidayRow=0;
    $calendarStudyleaveRow=0;
    $calendarAnnualLeaveRow=0;
    $calendarFloatingHolidayRow=0;
    $calendarOtherRow=0;

     while ($currentDayL <= $numberDaysL) {

          // Seventh column (Saturday) reached. Start a new row.

          // if ($dayOfWeek == 30) {

          //      $dayOfWeek = 0;
          //      $calendar .= "</tr><tr>";

          // }
          
          $currentDayRel = str_pad($currentDayL, 2, "0", STR_PAD_LEFT);
          
          $date = "$yearL-$monthL-$currentDayRel";
          $get_name = date('l', strtotime($date)); //get week day
          $day_name = substr($get_name, 0, 3); // Trim day name to 3 chars

          $leave_signal = false;
          $leave_signal_half = false;
          foreach ($leaveTypes as $key => $value) {
               if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavestatus']=='Approved'&&$value['appliedleavescount']=='0.5')
               {
                    $leave_signal_half=true;
                    break;
               }elseif (($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavestatus']=='Approved') {
                    $leave_signal=true;
                    break;
               }
          }
          $holiday_signal = false;
          foreach ($holiday_dates as $key => $value) {
          	if($value==$date){
          		$holiday_signal=true;
          	}
          }

          if($day_name=='Sun' || $day_name=='Sat')
          	$calendar .= "<td class=xl987473 style='border-top:none'>$currentDayL</td>";
          else if($holiday_signal)
          	$calendar .= "<td class=xl987473 style='border-top:none'>$currentDayL</td>";
          else
          	$calendar .= "<td class=xl1127473 style='border-top:none'>$currentDayL</td>";
          $time = '';
          $time = '';
          $dump = '';
          foreach ($sentTimesSheets as $key => $value) {
          	if($value[$date]!=null)
          	{
          		$time=$value[$date];
          		break;
          	}else{
          		$time = '00:00';
          	}
          }
          // $totalTime += decimalHours($time);
          // var_dump($time);
          // var_dump($sentTimesSheets);
          // var_dump($date);
          // die();

          foreach ($sentTimesSheets as $key => $value) {
            if($day_name=='Sun' || $day_name=='Sat')
              ${'calendar'.$key} .= "<td class=xl987473 style='border-top:none'> </td>";
            else if($holiday_signal)
              ${'calendar'.$key} .= "<td class=xl987473 style='border-top:none'> </td>";
            else if($leave_signal)
              ${'calendar'.$key} .= "<td class=xl987473 style='border-top:none'> </td>";
            else{
                foreach ($value as $ke => $val) {
                  if($val['date']==$date." 00:00:00")
                  {
                    // $time=$value[$date];
                    ${'totalTimeRow'.$key} += decimalHours($val['duration']);
                    ${'totalTimeColumn'.$ke} += decimalHours($val['duration']);
                    ${'totalTimeColumnwithLeave'.$ke} += decimalHours($val['duration']);
                    ${'calendar'.$key}.="<td class=xl1127473 style='border-top:none'>".$val['duration']."</td>";
                    break;
                  }else{
                    // ${'calendar'.$key}.="<td class=xl1127473 style='border-top:none'>00:00</td>";
                    // break;
                    // $time = '00:00';
                  }
              }
            }
          }

          foreach ($sentTimesSheets as $key => $value) {
            if($day_name=='Sun' || $day_name=='Sat')
              {
                $calendarSubTotalTime .= "<td class=xl987473 style='border-top:none'> </td>";
                break;
              }
            else if($holiday_signal){
              $calendarSubTotalTime .= "<td class=xl987473 style='border-top:none'>".clockalize(${'totalTimeColumn'.$ke})."</td>";
              $calendarSubTotalTimeSum += ${'totalTimeColumn'.$ke};
              break;
            }
            else if($leave_signal){
              $calendarSubTotalTime .= "<td class=xl987473 style='border-top:none'> </td>";
              break;
            }
            else{
                foreach ($value as $ke => $val) {
                  if($val['date']==$date." 00:00:00")
                  {
                    $calendarSubTotalTime .= "<td class=xl987473 width=37 style='width:28pt'>".clockalize(${'totalTimeColumn'.$ke})."</td>";
                    $calendarSubTotalTimeSum += ${'totalTimeColumn'.$ke};
                    break;
                  }
                }
                break;
              }
            }

          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarL .= "<td class=xl987473 style='border-top:none'>".$time."</td>";
          else if($holiday_signal)
          	$calendarL .= "<td class=xl987473 style='border-top:none'>".$time."</td>";
          else
          	$calendarL .= "<td class=xl1127473 style='border-top:none'>".$time."</td>";

          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarS .= "<td class=xl987473 style='border-top:none'>".$time."</td>";
          else if($holiday_signal)
          	$calendarS .= "<td class=xl987473 style='border-top:none'>".$time."</td>";
          else
          	$calendarS .= "<td class=xl1127473 style='border-top:none'>".$time."</td>";

          //official spacing
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarSpace .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarSpace .= "<td class=xl1127473 style='border-top:none'>&nbsp;</td>";

          	$calendarP .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";

          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==1&&$value['leavestatus']=='Approved')
          	{
          		$SickLeavetime="08:30";
              ${'totalLeaveColumn'.$currentDayL} += decimalHours("08:30");
              $calendarSubTotalLeaveSum += decimalHours("08:30");
              $calendarSickleaveRow += decimalHours("08:30");
          		break;
          	}else{
          		$SickLeavetime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==10&&$value['leavestatus']=='Approved')
          	{
          		$MaternityLeavetime="08:30";
              ${'totalLeaveColumn'.$currentDayL} += decimalHours("08:30");
              $calendarSubTotalLeaveSum += decimalHours("08:30");
              $calendarMaternityLeaveRow += decimalHours("08:30");
          		break;
          	}else{
          		$MaternityLeavetime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==13&&$value['leavestatus']=='Approved')
          	{
          		$PaternityLeavetime="08:30";
              ${'totalLeaveColumn'.$currentDayL} += decimalHours("08:30");
              $calendarSubTotalLeaveSum += decimalHours("08:30");
              $calendarPaternityLeaveRow += decimalHours("08:30");
          		break;
          	}else{
          		$PaternityLeavetime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==12&&$value['leavestatus']=='Approved')
          	{
          		$FamilyLeavetime="08:30";
              ${'totalLeaveColumn'.$currentDayL} += decimalHours("08:30");
              $calendarSubTotalLeaveSum += decimalHours("08:30");
              $calendarFloatingHolidayRow += decimalHours("08:30");
          		break;
          	}else{
          		$FamilyLeavetime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==5&&$value['leavestatus']=='Approved')
          	{
          		$PublicHolidaytime="08:30";
              ${'totalLeaveColumn'.$currentDayL} += decimalHours("08:30");
              $calendarSubTotalLeaveSum += decimalHours("08:30");
              $calendarPublicHolidayRow += decimalHours("08:30");
          		break;
          	}else{
          		$PublicHolidaytime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==6&&$value['leavestatus']=='Approved')
          	{
          		$Studyleavetime="08:30";
              ${'totalLeaveColumn'.$currentDayL} += decimalHours("08:30");
              $calendarSubTotalLeaveSum += decimalHours("08:30");
              $calendarStudyleaveRow += decimalHours("08:30");
          		break;
          	}else{
          		$Studyleavetime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==7&&$value['leavestatus']=='Approved')
          	{
          		$AnnualLeavetime="08:30";
              ${'totalLeaveColumn'.$currentDayL} += decimalHours("08:30");
              $calendarSubTotalLeaveSum += decimalHours("08:30");
              $calendarAnnualLeaveRow += decimalHours("08:30");
          		break;
          	}else{
          		$AnnualLeavetime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==8&&$value['leavestatus']=='Approved')
          	{
          		$FloatingHolidaytime="08:30";
              ${'totalLeaveColumn'.$currentDayL} += decimalHours("08:30");
              $calendarSubTotalLeaveSum += decimalHours("08:30");
              $calendarFloatingHolidayRow += decimalHours("08:30");
          		break;
          	}else{
          		$FloatingHolidaytime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']!=8&&$value['leavetypeid']!=15&&$value['leavetypeid']!=6&&$value['leavetypeid']!=5&&$value['leavetypeid']!=12&&$value['leavetypeid']!=13&&$value['leavetypeid']!=10&&$value['leavetypeid']!=1&&$value['leavestatus']=='Approved')
          	{
          		$Othertime="08:30";
              ${'totalLeaveColumn'.$currentDayL} += decimalHours("08:30");
              $calendarSubTotalLeaveSum += decimalHours("08:30");
              $calendarOtherRow += decimalHours("08:30");
          		break;
          	}else{
          		$Othertime = '';
          	}
          }
          //official leave header
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarLeaveHeader .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarLeaveHeader .= "<td class=xl1127473 style='border-top:none'>&nbsp;</td>";

          //offical leave
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarSickleave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarSickleave .= "<td class=xl1127473 style='border-top:none'>$SickLeavetime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarMaternityLeave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarMaternityLeave .= "<td class=xl1127473 style='border-top:none'>$MaternityLeavetime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarPaternityLeave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarPaternityLeave .= "<td class=xl1127473 style='border-top:none'>$PaternityLeavetime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarFamilyLeave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarFamilyLeave .= "<td class=xl1127473 style='border-top:none'>$FamilyLeavetime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarPublicHoliday .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarPublicHoliday .= "<td class=xl1127473 style='border-top:none'>$PublicHolidaytime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarStudyleave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarStudyleave .= "<td class=xl1127473 style='border-top:none'>$Studyleavetime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarAnnualLeave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarAnnualLeave .= "<td class=xl1127473 style='border-top:none'>$AnnualLeavetime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarFloatingHoliday .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarFloatingHoliday .= "<td class=xl1127473 style='border-top:none'>$FloatingHolidaytime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarOther .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarOther .= "<td class=xl1127473 style='border-top:none'>$Othertime</td>";

          // $calendarSubTotalLeave .= "<td class=xl1877473 width=37 style='width:28pt'>0</td>";
          foreach ($sentTimesSheets as $key => $value) {
            if($day_name=='Sun' || $day_name=='Sat'){
              $calendarSubTotalLeave .= "<td class=xl987473 style='border-top:none'> </td>";
              break;
            }
            else if($holiday_signal){
              $calendarSubTotalLeave .= "<td class=xl987473 style='border-top:none'> </td>";
              break;
            }
            else if($leave_signal){
              $calendarSubTotalLeave .= "<td class=xl987473 style='border-top:none'>".clockalize(${'totalLeaveColumn'.$currentDayL})."</td>";
              break;
            }
            else{
                foreach ($value as $ke => $val) {
                  if($val['date']==$date." 00:00:00")
                  {
                    $calendarSubTotalLeave .= "<td class=xl1877473 width=37 style='width:28pt'>".clockalize(${'totalLeaveColumn'.$currentDayL})."</td>";
                    break;
                  }
                }
                break;
              }
            }

          foreach ($sentTimesSheets as $key => $value) {
            if($day_name=='Sun' || $day_name=='Sat'){
              $caledarGrandTotal .= "<td class=xl987473 style='border-top:none'> </td>";
              break;
            }
            else if($holiday_signal){
              $caledarGrandTotal .= "<td class=xl987473 style='border-top:none'>".clockalize(decimalSum(0,${'totalTimeColumn'.$ke}))."</td>";
              break;
            }
            else if($leave_signal){
              $caledarGrandTotal .= "<td class=xl987473 style='border-top:none'>".clockalize(decimalSum(${'totalLeaveColumn'.$currentDay},0))."</td>";
              break;
            }
            else{
                foreach ($value as $ke => $val) {
                  if($val['date']==$date." 00:00:00")
                  {
                    $caledarGrandTotal .= "<td class=xl1877473 width=37 style='width:28pt'>".clockalize(decimalSum(${'totalLeaveColumn'.$currentDay},${'totalTimeColumn'.$ke}))."</td>";
                    break;
                  }
                }
                break;
              }
            }


          // $caledarGrandTotal .= "<td class=xl1877473 width=37 style='width:28pt'>0</td>";
          
          // $calendarL .= "<td class='day $day_name' rel='$date'>$currentDayL</td>";

          // Increment counters
 
          $currentDayL++;
          $dayOfWeekL++;

     }


     while ($currentDay <= $numberDays) {

          // Seventh column (Saturday) reached. Start a new row.

          // if ($dayOfWeek == 30) {

          //      $dayOfWeek = 0;
          //      $calendar .= "</tr><tr>";

          // }
          
          $currentDayRel = str_pad($currentDay, 2, "0", STR_PAD_LEFT);
          
          $date = "$year-$month-$currentDayRel";
          $get_name = date('l', strtotime($date)); //get week day
          $day_name = substr($get_name, 0, 3); // Trim day name to 3 chars

          $leave_signal = false;
          $leave_signal_half = false;
          foreach ($leaveTypes as $key => $value) {
               if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavestatus']=='Approved'&&$value['appliedleavescount']=='0.5')
               {
                    $leave_signal_half=true;
                    break;
               }elseif (($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavestatus']=='Approved') {
                    $leave_signal=true;
                    break;
               }
          }
          $holiday_signal = false;
          foreach ($holiday_dates as $key => $value) {
          	if($value==$date){
          		$holiday_signal=true;
          	}
          }

          if($day_name=='Sun' || $day_name=='Sat')
          	$calendar .= "<td class=xl987473 style='border-top:none'>$currentDay</td>";
          else if($holiday_signal)
          	$calendar .= "<td class=xl987473 style='border-top:none'>$currentDay</td>";
          else
          	$calendar .= "<td class=xl1127473 style='border-top:none'>$currentDay</td>";

          $time = '';
          foreach ($sentTimesSheets as $key => $value) {
          	if($value[$date]!=null)
          	{
          		$time=$value[$date];
          		break;
          	}else{
          		$time = '00:00';
          	}
          }

          foreach ($sentTimesSheets as $key => $value) {
            if($day_name=='Sun' || $day_name=='Sat')
              ${'calendar'.$key} .= "<td class=xl987473 style='border-top:none'> </td>";
            else if($holiday_signal)
              ${'calendar'.$key} .= "<td class=xl987473 style='border-top:none'> </td>";
            else if($leave_signal)
              ${'calendar'.$key} .= "<td class=xl1127473 style='border-top:none'> </td>";
            else{
                foreach ($value as $ke => $val) {
                  if($val['date']==$date." 00:00:00")
                  {
                    // $time=$value[$date];
                    ${'totalTimeRow'.$key} += decimalHours($val['duration']);
                    ${'totalTimeColumn'.$ke} += decimalHours($val['duration']);
                    ${'totalTimeColumnwithLeave'.$ke} += decimalHours($val['duration']);
                    ${'calendar'.$key}.="<td class=xl1127473 style='border-top:none'>".$val['duration']."</td>";
                    break;
                  }else{
                    // ${'calendar'.$key}.="<td class=xl1127473 style='border-top:none'>00:00</td>";
                    // break;
                    // $time = '00:00';
                  }
              }
            }
          }

          foreach ($sentTimesSheets as $key => $value) {
            if($day_name=='Sun' || $day_name=='Sat')
              {
                $calendarSubTotalTime .= "<td class=xl987473 style='border-top:none'> </td>";
                break;
              }
            else if($holiday_signal){
              $calendarSubTotalTime .= "<td class=xl987473 style='border-top:none'>".clockalize(${'totalTimeColumn'.$ke})."</td>";
              $calendarSubTotalTimeSum += ${'totalTimeColumn'.$ke};
              break;
            }
            else if($leave_signal){
              $calendarSubTotalTime .= "<td class=xl987473 style='border-top:none'> </td>";
              break;
            }
            else{
                foreach ($value as $ke => $val) {
                  if($val['date']==$date." 00:00:00")
                  {
                    $calendarSubTotalTime .= "<td class=xl987473 width=37 style='width:28pt'>".clockalize(${'totalTimeColumn'.$ke})."</td>";
                    $calendarSubTotalTimeSum += ${'totalTimeColumn'.$ke};
                    break;
                  }
                }
                break;
              }
            }

          // $totalTime += decimalHours($time);
          // var_dump($time);
          // var_dump($sentTimesSheets);
          // var_dump($date);
          // die();

          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarL .= "<td class=xl987473 style='border-top:none'>".$time."</td>";
          else if($holiday_signal)
          	$calendarL .= "<td class=xl987473 style='border-top:none'>".$time."</td>";
          else
          	$calendarL .= "<td class=xl1127473 style='border-top:none'>".$time."</td>";

          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarS .= "<td class=xl987473 style='border-top:none'>".$time."</td>";
          else if($holiday_signal)
          	$calendarS .= "<td class=xl987473 style='border-top:none'>".$time."</td>";
          else
          	$calendarS .= "<td class=xl1127473 style='border-top:none'>".$time."</td>";

          //official spacing
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarSpace .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else if($holiday_signal)
          	$calendarSpace .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarSpace .= "<td class=xl1127473 style='border-top:none'>&nbsp;</td>";

          $calendarP .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";

          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==1&&$value['leavestatus']=='Approved')
          	{
          		$SickLeavetime="08:30";
              ${'totalLeaveColumn'.$currentDay} += decimalHours("08:30");
              $calendarSubTotalLeaveSum += decimalHours("08:30");
              $calendarSickleaveRow += decimalHours("08:30");
          		break;
          	}else{
          		$SickLeavetime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==10&&$value['leavestatus']=='Approved')
          	{
          		$MaternityLeavetime="08:30";
              ${'totalLeaveColumn'.$currentDay} += decimalHours("08:30");
              $calendarSubTotalLeaveSum += decimalHours("08:30");
              $calendarMaternityLeaveRow += decimalHours("08:30");
          		break;
          	}else{
          		$MaternityLeavetime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==13&&$value['leavestatus']=='Approved')
          	{
          		$PaternityLeavetime="08:30";
              ${'totalLeaveColumn'.$currentDay} += decimalHours("08:30");
              $calendarSubTotalLeaveSum += decimalHours("08:30");
              $calendarPaternityLeaveRow += decimalHours("08:30");
          		break;
          	}else{
          		$PaternityLeavetime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==12&&$value['leavestatus']=='Approved')
          	{
          		$FamilyLeavetime="08:30";
              ${'totalLeaveColumn'.$currentDay} += decimalHours("08:30");
              $calendarSubTotalLeaveSum += decimalHours("08:30");
              $calendarFamilyLeaveRow += decimalHours("08:30");
          		break;
          	}else{
          		$FamilyLeavetime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==5&&$value['leavestatus']=='Approved')
          	{
          		$PublicHolidaytime="08:30";
              ${'totalLeaveColumn'.$currentDay} += decimalHours("08:30");
              $calendarSubTotalLeaveSum += decimalHours("08:30");
              $calendarPublicHolidayRow += decimalHours("08:30");
          		break;
          	}else{
          		$PublicHolidaytime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==6&&$value['leavestatus']=='Approved')
          	{
          		$Studyleavetime="08:30";
              ${'totalLeaveColumn'.$currentDay} += decimalHours("08:30");
              $calendarSubTotalLeaveSum += decimalHours("08:30");
              $calendarStudyleaveRow += decimalHours("08:30");
          		break;
          	}else{
          		$Studyleavetime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==15&&$value['leavestatus']=='Approved')
          	{
          		$AnnualLeavetime="08:30";
              ${'totalLeaveColumn'.$currentDay} += decimalHours("08:30");
              $calendarSubTotalLeaveSum += decimalHours("08:30");
              $calendarAnnualLeaveRow += decimalHours("08:30");
          		break;
          	}else{
          		$AnnualLeavetime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']==8&&$value['leavestatus']=='Approved')
          	{
          		$FloatingHolidaytime="08:30";
              ${'totalLeaveColumn'.$currentDay} += decimalHours("08:30");
              $calendarSubTotalLeaveSum += decimalHours("08:30");
              $calendarFloatingHolidayRow += decimalHours("08:30");
          		break;
          	}else{
          		$FloatingHolidaytime = '';
          	}
          }
          foreach ($leaveTypes as $key => $value) {
          	if(($date>=$value['from_date'])&&($date<=$value['to_date'])&&$value['leavetypeid']!=8&&$value['leavetypeid']!=15&&$value['leavetypeid']!=6&&$value['leavetypeid']!=5&&$value['leavetypeid']!=12&&$value['leavetypeid']!=13&&$value['leavetypeid']!=10&&$value['leavetypeid']!=1&&$value['leavestatus']=='Approved')
          	{
          		$Othertime="08:30";
              ${'totalLeaveColumn'.$currentDay} += decimalHours("08:30");
              $calendarSubTotalLeaveSum += decimalHours("08:30");
              $calendarOtherRow += decimalHours("08:30");
          		break;
          	}else{
          		$Othertime = '';
          	}
          }
          //official leave header
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarLeaveHeader .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else if($holiday_signal)
          	$calendarLeaveHeader .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarLeaveHeader .= "<td class=xl1127473 style='border-top:none'>&nbsp;</td>";

          //offical leave
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarSickleave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else if($holiday_signal)
          	$calendarSickleave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarSickleave .= "<td class=xl1127473 style='border-top:none'>$SickLeavetime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarMaternityLeave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else if($holiday_signal)
          	$calendarMaternityLeave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarMaternityLeave .= "<td class=xl1127473 style='border-top:none'>$MaternityLeavetime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarPaternityLeave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else if($holiday_signal)
          	$calendarPaternityLeave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarPaternityLeave .= "<td class=xl1127473 style='border-top:none'>$PaternityLeavetime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarFamilyLeave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else if($holiday_signal)
          	$calendarFamilyLeave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarFamilyLeave .= "<td class=xl1127473 style='border-top:none'>$FamilyLeavetime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarPublicHoliday .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else if($holiday_signal)
          	$calendarPublicHoliday .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarPublicHoliday .= "<td class=xl1127473 style='border-top:none'>$PublicHolidaytime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarStudyleave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else if($holiday_signal)
          	$calendarStudyleave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarStudyleave .= "<td class=xl1127473 style='border-top:none'>$Studyleavetime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarAnnualLeave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else if($holiday_signal)
          	$calendarAnnualLeave .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarAnnualLeave .= "<td class=xl1127473 style='border-top:none'>$AnnualLeavetime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarFloatingHoliday .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else if($holiday_signal)
          	$calendarFloatingHoliday .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarFloatingHoliday .= "<td class=xl1127473 style='border-top:none'>$FloatingHolidaytime</td>";
          
          if($day_name=='Sun' || $day_name=='Sat')
          	$calendarOther .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else if($holiday_signal)
          	$calendarOther .= "<td class=xl987473 style='border-top:none'>&nbsp;</td>";
          else
          	$calendarOther .= "<td class=xl1127473 style='border-top:none'>$Othertime</td>";

          // $calendarSubTotalLeave .= "<td class=xl1877473 width=37 style='width:28pt'>0</td>";

          foreach ($sentTimesSheets as $key => $value) {
            if($day_name=='Sun' || $day_name=='Sat'){
              $calendarSubTotalLeave .= "<td class=xl987473 style='border-top:none'> </td>";
              break;
            }
            else if($holiday_signal){
              $calendarSubTotalLeave .= "<td class=xl987473 style='border-top:none'> </td>";
              break;
            }
            else if($leave_signal){
              $calendarSubTotalLeave .= "<td class=xl987473 style='border-top:none'>".clockalize(${'totalLeaveColumn'.$currentDay})."</td>";
              break;
            }
            else{
                foreach ($value as $ke => $val) {
                  if($val['date']==$date." 00:00:00")
                  {
                    $calendarSubTotalLeave .= "<td class=xl1877473 width=37 style='width:28pt'>".clockalize(${'totalLeaveColumn'.$currentDay})."</td>";
                    break;
                  }
                }
                break;
              }
            }

          foreach ($sentTimesSheets as $key => $value) {
            if($day_name=='Sun' || $day_name=='Sat'){
              $caledarGrandTotal .= "<td class=xl987473 style='border-top:none'> </td>";
              break;
            }
            else if($holiday_signal){
              $caledarGrandTotal .= "<td class=xl987473 style='border-top:none'>".clockalize(decimalSum(0,${'totalTimeColumn'.$ke}))."</td>";
              break;
            }
            else if($leave_signal){
              $caledarGrandTotal .= "<td class=xl987473 width=37 style='border-top:none'>".clockalize(decimalSum(${'totalLeaveColumn'.$currentDay},0))."</td>";
              break;
            }
            else{
                foreach ($value as $ke => $val) {
                  if($val['date']==$date." 00:00:00")
                  {
                    $caledarGrandTotal .= "<td class=xl1877473 width=37 style='width:28pt'>".clockalize(decimalSum(${'totalLeaveColumn'.$currentDay},${'totalTimeColumn'.$ke}))."</td>";
                    break;
                  }
                }
                break;
              }
            }

          // $caledarGrandTotal .= "<td class=xl1877473 width=37 style='width:28pt'>0</td>";

          // $calendar .= "<td class=xl1127473 width=37 style='border-top:none;width:28pt'>$currentDay</td>";
          // $calendarL .= "<td class='day $day_name' rel='$date'>$currentDay</td>";
          if ($currentDay==$numberDays) {
            foreach ($sentTimesSheets as $key => $value) {
              ${'calendar'.$key} .= "<td class=xl1127473 style='border-top:none'>".clockalize(${'totalTimeRow'.$key})."</td>";
            }
          	$calendarL .= "<td class=xl1127473 style='border-top:none'>".clockalize($totalTime)."</td>";
          	$calendarS .= "<td class=xl1127473 style='border-top:none'>".clockalize($totalTime)."</td>";
          	$calendarSpace .= "<td class=xl1127473 style='border-top:none'>&nbsp;</td>";
          	$calendarSickleave .= "<td class=xl1127473 style='border-top:none'>".clockalize($calendarSickleaveRow)."</td>";
          	$calendarMaternityLeave .= "<td class=xl1127473 style='border-top:none'>".clockalize($calendarMaternityLeaveRow)."</td>";
          	$calendarPaternityLeave .= "<td class=xl1127473 style='border-top:none'>".clockalize($calendarPaternityLeaveRow)."</td>";
          	$calendarFamilyLeave .= "<td class=xl1127473 style='border-top:none'>".clockalize($calendarFamilyLeaveRow)."</td>";
          	$calendarPublicHoliday .= "<td class=xl1127473 style='border-top:none'>".clockalize($calendarPublicHolidayRow)."</td>";
          	$calendarStudyleave .= "<td class=xl1127473 style='border-top:none'>".clockalize($calendarStudyleaveRow)."</td>";
          	$calendarAnnualLeave .= "<td class=xl1127473 style='border-top:none'>".clockalize($calendarAnnualLeaveRow)."</td>";
          	$calendarFloatingHoliday .= "<td class=xl1127473 style='border-top:none'>".clockalize($calendarFloatingHolidayRow)."</td>";
          	$calendarOther .= "<td class=xl1127473 style='border-top:none'>".clockalize($calendarOtherRow)."</td>";
          	$calendarLeaveHeader .= "<td class=xl1127473 style='border-top:none'>&nbsp;</td>";
          	$calendarSubTotalLeave .= "<td class=xl987473 width=37 style='width:28pt'>".clockalize($calendarSubTotalLeaveSum)."</td>";
            $calendarSubTotalTime .= "<td class=xl987473 width=37 style='width:28pt'>".clockalize($calendarSubTotalTimeSum)."</td>";
          	$caledarGrandTotal .= "<td class=xl987473 width=37 style='width:28pt'>".clockalize(decimalSum($calendarSubTotalTimeSum,$calendarSubTotalLeaveSum))."</td>";
          }
          // Increment counters
 
          $currentDay++;
          $dayOfWeek++;

     }
     
     

     // Complete the row of the last week in month, if necessary

     // if ($dayOfWeek != 7) { 
     
     //      $remainingDays = 7 - $dayOfWeek;
     //      $calendar .= "<td colspan='$remainingDays'>&nbsp;</td>"; 

     // }
     
     $calendar .= "</tr>";
     // $calendarL .= "</tr>";

     // $calendar .= $calendarL;

     // $calendar .= "</table>";
     $calendar .= "<tr class=xl887473 height=26 style='mso-height-source:userset;height:19.5pt'>
  <td height=26 class=xl1307473 style='height:19.5pt;border-top:none'>Project</td>
  <td class=xl1317473 style='border-top:none;border-left:none'>Project Code</td>
  <td class=xl1327473 style='border-top:none;border-left:none'>Location</td>";
  	$calendar .= $calendarP;
  	$calendar .= "</tr>";

 if($sentTimesSheets!=null){$calendar .= "<tr class=xl897473 height=31 style='mso-height-source:userset;height:23.25pt'>";}
 foreach ($sentTimesSheets as $key => $value) {
       ${'calendar'.$key}.="</tr>";
       $calendar .= ${'calendar'.$key};
     }
     // var_dump($calendarL);
 // $calendar .= $calendarL."</tr>";
 $calendar .= $calendarSpace;
 $calendar .= $calendarSpace;
 $calendar .= $calendarSpace;
 $calendar .= $calendarSpace;

  if($sentTimesSheets!=null){$calendar .= "</tr>".$calendarSubTotalTime;}
  // $calendar .= $calendarS."</tr>";
  $calendarSpace .= "</tr>";

  // $calendar .= $calendarSpace;
  // $calendar .= $calendarSpace;
  // $calendar .= $calendarSpace;
  // $calendar .= $calendarSpace;
  $calendar .= $calendarLeaveHeader;
  $calendar .= "</tr>";

  $calendar .= $calendarSickleave;
  $calendar .= "</tr>";
  $calendar .= $calendarMaternityLeave;
  $calendar .= "</tr>";
  $calendar .= $calendarPaternityLeave;
  $calendar .= "</tr>";
  $calendar .= $calendarFamilyLeave;
  $calendar .= "</tr>";
  $calendar .= $calendarPublicHoliday;
  $calendar .= "</tr>";
  $calendar .= $calendarStudyleave;
  $calendar .= "</tr>";
  $calendar .= $calendarAnnualLeave;
  $calendar .= "</tr>";
  $calendar .= $calendarFloatingHoliday;
  $calendar .= "</tr>";
  $calendar .= $calendarOther;
  $calendar .= "</tr>";
  if($sentTimesSheets!=null){$calendar .= $calendarSubTotalLeave;
  $calendar .= "</tr>";}
  if($sentTimesSheets!=null){$calendar .= $caledarGrandTotal;
  $calendar .= "</tr>";}


     return $calendar;

}

 ?>
<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>
<?php

	$data = $this->data;
	$startday_m=$this->startday_m;
	$endday_m=$this->endday_m;
	$min_year=$this->min_year;
	$type = $this->type;
	$selYrMon = $this->selYrMon;
	$selectedYrMon = explode('-', $selYrMon);
	$user_id = $this->user_id;
	$manager_id = $this->manager_id;
	$hidweek = $this->hidweek;
	$tm_role = $this->tm_role;
	$emplistflag = $this->emplistflag;
	$project_ids = $this->project_ids;
?>
<script type="text/javascript">
$(document).ready(function(){
	$("#monthweek li").click(function() {
		$('#emp_timesheet_view').html('');
		var status=$(this).attr('id');
		$('#monthweek li').removeClass('dis_none');
	    $(this).addClass('dis_none');  
	    $('#timesheetView').val(status);
	    var selmn=$('#idhidselmn').val();
	    var emplistflag = $('#emplistflag').val();
	    if(status=='week')
	    {  
			$("#show_cal").css("display", "block");
	    	emp_display_weeks_monthly(selmn,'<?php echo $data->id;?>','',emplistflag);
	    }else{
	    	$('#idweeks_display').html('');
	    	$("#show_cal").css("display", "none");
	    	displayEmpTimesheetMonthly(selmn,emplistflag);
	    }
	});
});


</script>
<input type="hidden" id="timesheetView" name="timesheetView" value="month" />
<input type="hidden" id="idhidselmn" value="<?php echo date('Y-m');?>"/>
<input type="hidden" id="selYrMon" value="<?php echo $selYrMon;?>"/>
<input type="hidden" id="sheetType" value="<?php echo $type;?>"/>
<input type="hidden" id="manager_id" value="<?php echo $manager_id;?>"/>
<input type="hidden" id="user_id" value="<?php echo $user_id;?>"/>
<input type="hidden" id="emplistflag" value="<?php echo $emplistflag;?>"/>
<input type="hidden" id="project_ids" value="<?php echo $project_ids;?>"/>
<input type="hidden" id="hidweek" value="<?php echo $hidweek;?>"/>
<div class="container">
	<div class="left_container">
    	<div class="emp_approve_box">
        	<div class="emp_approve_box_left">
            	<!-- label>Employee</label -->
                <span id="emp_name"></span>
            </div>
            <!-- div class="emp_approve_box_right">
           		 <label>Total Hours</label>
                <span id="emp_total_hours">00:00</span>
            </div -->
            <div class="row_info">
            	<label>Status</label>
                <span class="no_entry" id=""> <?php echo $this->status[0]['status']; ?> </span>
            </div>
            <div class="row_info">
            	<label>Manager</label>
                <span id="emp_manager_name"></span>
            </div>
            <div class="right-btn-block" id="emp_buttons_display"></div>
        </div>
    </div>
	<div class="right_content">
		<div id="grid_msg" style="display:none;" class='ml-alert-1-success'></div>
		<div class="control_option cal_single_view flt_lft" style="display: none;">
		
			<ul id="monthweek" class="month_view_link">
				 <li class="link_txt" <?php if($type == "month") { ?> class="dis_none" <?php } ?> id="month" title="Month">Monthly View</li>
		         <li class="link_txt" <?php if($type == "week") { ?> class="dis_none" <?php } ?>id="week" title="Week">Weekly View</li>
			</ul>
		
			<div class="new-form-ui month_picker" id="show_cal" style='display:none;'>
				<div class="division">
					<input id="start_date" class="brdr_none hasDatepicker" type="text" onfocus="this.blur()" readonly="readonly" value="" name="start_date">
					<img class="ui-datepicker-trigger" src="<?php echo $this->baseUrl().'/public/media/timemanagement/';?>images/cal_new.png" alt="" title="">
				</div>
		    </div>
			
		    <div id="idweek_status_display" style="display: none;"></div>
		</div>
		<!-- <div id="idweeks_display" class="emp_week_view emp_time_week_view"></div> -->
		<div id="emp_timesheet_view" class="emp_timesheet_view emp_timesheet_view_top_mar">
		</div>
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link rel=File-List
href="1.10.%202020%20Timesheet%20October%202020_files/filelist.xml">
<style id="1.10. 2020 Timesheet October 2020_7473_Styles">
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
-->
</style>
<link rel="stylesheet" type="text/css" href="<?php echo MEDIA_PATH; ?>css/timesheetreport.css">
</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="1.10. 2020 Timesheet October 2020_7473" align=center
x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=1724 class=xl727473
 style='border-collapse:collapse;table-layout:fixed;width:1300pt;'>
 <col class=xl727473 width=99 style='mso-width-source:userset;mso-width-alt:
 3620;width:74pt'>
 <col class=xl897473 width=73 style='mso-width-source:userset;mso-width-alt:
 2669;width:55pt'>
 <col class=xl897473 width=66 style='mso-width-source:userset;mso-width-alt:
 2413;width:50pt'>
 <col class=xl727473 width=37 span=7 style='mso-width-source:userset;
 mso-width-alt:1353;width:28pt'>
 <col class=xl2597473 width=37 span=2 style='mso-width-source:userset;
 mso-width-alt:1353;width:28pt'>
 <col class=xl727473 width=37 span=5 style='mso-width-source:userset;
 mso-width-alt:1353;width:28pt'>
 <col class=xl2597473 width=37 style='mso-width-source:userset;mso-width-alt:
 1353;width:28pt'>
 <col class=xl727473 width=37 span=17 style='mso-width-source:userset;
 mso-width-alt:1353;width:28pt'>
 <col class=xl727473 width=39 span=5 style='mso-width-source:userset;
 mso-width-alt:1426;width:29pt'>
 <col class=xl727473 width=0 style='display:none;mso-width-source:userset;
 mso-width-alt:1133'>
 <col class=xl727473 width=0 style='display:none;mso-width-source:userset;
 mso-width-alt:1133'>
 <col class=xl727473 width=43 style='mso-width-source:userset;mso-width-alt:
 1572;width:32pt'>
 <col class=xl727473 width=0 style='display:none;mso-width-source:userset;
 mso-width-alt:1682'>
 <col class=xl727473 width=0 style='display:none;mso-width-source:userset;
 mso-width-alt:1682'>
 <col class=xl727473 width=0 style='display:none;mso-width-source:userset;
 mso-width-alt:2340'>
 <col class=xl727473 width=0 style='display:none;mso-width-source:userset;
 mso-width-alt:2340'>
 <col class=xl727473 width=0 style='display:none;mso-width-source:userset;
 mso-width-alt:2340'>
 <col class=xl727473 width=64 style='width:48pt'>
 <tr class=xl727473 height=37 style='mso-height-source:userset;height:27.75pt'>
  <td height=37 class=xl1207473 width=99 style='height:27.75pt;width:74pt'><a
  name="RANGE!A1:AR37">Name</a></td>
  <td colspan=9 class=xl2727473 width=398 style='width:301pt'><?php echo $this->fullName; ?></td>
  <td class=xl727473 width=37 style='width:28pt'></td>
  <td class=xl727473 width=37 style='width:28pt'></td>
  <td class=xl727473 width=37 style='width:28pt'></td>
  <td class=xl1217473 width=37 style='width:28pt'></td>
  <td class=xl727473 width=37 style='width:28pt'></td>
  <td class=xl727473 width=37 style='width:28pt'></td>
  <td class=xl727473 width=37 style='width:28pt'></td>
  <td class=xl727473 width=37 style='width:28pt'></td>
  <td class=xl727473 width=37 style='width:28pt'></td>
  <td class=xl727473 width=37 style='width:28pt'></td>
  <td class=xl727473 width=37 style='width:28pt'></td>
  <td class=xl727473 width=37 style='width:28pt'></td>
  <td class=xl727473 width=37 style='width:28pt'></td>
  <td class=xl727473 width=37 style='width:28pt'></td>
  <td class=xl727473 width=37 style='width:28pt'></td>
  <td class=xl1227473 width=37 style='width:28pt'></td>
  <td class=xl1227473 width=37 style='width:28pt'></td>
  <td class=xl1227473 width=37 style='width:28pt'></td>
  <td class=xl1227473 width=37 style='width:28pt'></td>
  <td class=xl1227473 width=37 style='width:28pt'></td>
  <td class=xl1227473 width=37 style='width:28pt'></td>
  <td class=xl1227473 width=37 style='width:28pt'></td>
  <td class=xl1227473 width=37 style='width:28pt'></td>
  <td class=xl1227473 width=37 style='width:28pt'></td>
  <td class=xl1227473 width=37 style='width:28pt'></td>
  <td class=xl1227473 width=39 style='width:29pt'></td>
  <td class=xl1227473 width=39 style='width:29pt'></td>
  <td class=xl1227473 width=39 style='width:29pt'></td>
  <td class=xl1227473 width=39 style='width:29pt'></td>
  <td class=xl1227473 width=39 style='width:29pt'></td>
  <td class=xl1227473 width=0></td>
  <td class=xl1227473 width=0></td>
  <td class=xl1227473 width=43 style='width:32pt'></td>
  <td class=xl727473 width=0></td>
  <td class=xl727473 width=0></td>
  <td class=xl727473 width=0></td>
  <td class=xl727473 width=0></td>
  <td class=xl727473 width=0></td>
  <td class=xl727473 width=64 style='width:48pt'></td>
 </tr>
 <tr class=xl727473 height=28 style='mso-height-source:userset;height:21.0pt'>
  <td height=28 class=xl1237473 style='height:21.0pt'></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1247473>&nbsp;</td>
  <td class=xl1247473>&nbsp;</td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl1237473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
 </tr>
		<?php 
			echo build_calendar($this->month,$this->year,$dateArray,$this->TMSCData,$this->sentTimesSheets,$this->leaveTypes,$this->empHolidaysWeekends);
		 ?>
<tr class=xl727473 height=12 style='mso-height-source:userset;height:9.0pt'>
  <td height=12 class=xl2457473 style='height:9.0pt'>&nbsp;</td>
  <td class=xl2467473></td>
  <td class=xl2467473></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2487473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
 </tr>
 <tr class=xl727473 height=26 style='mso-height-source:userset;height:20.1pt'>
  <td height=26 class=xl2457473 style='height:20.1pt'>LOE Allocation</td>
  <td class=xl2467473></td>
  <td class=xl2467473></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2487473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
 </tr>
 <tr class=xl727473 height=26 style='mso-height-source:userset;height:20.1pt'>
  <td height=26 class=xl747473 colspan=2 style='height:20.1pt'>Actual Hours
  Worked</td>
  <td class=xl747473>&nbsp;</td>
  <td colspan=5 class=xl2647473><span style='mso-spacerun:yes'> </span></td>
  <td colspan=5 class=xl2657473><span style='mso-spacerun:yes'> </span></td>
  <td colspan=5 class=xl2337473 width=185 style='width:140pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td colspan=5 class=xl2347473><span style='mso-spacerun:yes'> </span></td>
  <td colspan=5 class=xl2347473><span style='mso-spacerun:yes'> </span></td>
  <td colspan=5 class=xl2347473><span style='mso-spacerun:yes'> </span></td>
  <td colspan=5 class=xl2347473><span style='mso-spacerun:yes'> </span></td>
  <td colspan=5 rowspan=2 class=xl2667473 width=121 style='width:90pt'>&nbsp;</td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
 </tr>
 <tr class=xl727473 height=26 style='mso-height-source:userset;height:20.1pt'>
  <td height=26 class=xl747473 style='height:20.1pt'>&nbsp;</td>
  <td class=xl747473>&nbsp;</td>
  <td class=xl747473>&nbsp;</td>
  <td colspan=2 class=xl2337473 width=74 style='width:56pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td colspan=2 class=xl2337473 width=74 style='width:56pt'>&nbsp;</td>
  <td class=xl717473 width=37 style='width:28pt'>&nbsp;</td>
  <td colspan=2 class=xl2337473 width=74 style='width:56pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td colspan=2 class=xl2337473 width=74 style='width:56pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl2347473>&nbsp;</td>
  <td colspan=2 class=xl2337473 width=74 style='width:56pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td colspan=2 class=xl2337473 width=74 style='width:56pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl2347473>&nbsp;</td>
  <td colspan=2 class=xl2337473 width=74 style='width:56pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td colspan=2 class=xl2337473 width=74 style='width:56pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl2347473>&nbsp;</td>
  <td colspan=2 class=xl2337473 width=74 style='width:56pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td colspan=2 class=xl2337473 width=74 style='width:56pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl2347473>&nbsp;</td>
  <td colspan=2 class=xl2337473 width=74 style='width:56pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td colspan=2 class=xl2337473 width=74 style='width:56pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl2337473 width=37 style='width:28pt'>&nbsp;</td>
  <td colspan=2 class=xl2337473 width=74 style='width:56pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td colspan=2 class=xl2337473 width=78 style='width:58pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl2347473>&nbsp;</td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
 </tr>
 <tr class=xl727473 height=19 style='mso-height-source:userset;height:14.25pt'>
  <td height=19 class=xl2497473 style='height:14.25pt'></td>
  <td class=xl2467473></td>
  <td class=xl2467473></td>
  <td colspan=2 class=xl1857473><span style='mso-spacerun:yes'> </span></td>
  <td class=xl727473></td>
  <td colspan=2 class=xl2517473 width=74 style='width:56pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td colspan=2 class=xl1857473><span style='mso-spacerun:yes'> </span></td>
  <td class=xl2477473></td>
  <td colspan=2 class=xl2527473><span style='mso-spacerun:yes'> </span></td>
  <td colspan=2 class=xl1857473><span style='mso-spacerun:yes'> </span></td>
  <td class=xl2477473></td>
  <td colspan=2 class=xl2527473><span style='mso-spacerun:yes'> </span></td>
  <td colspan=2 class=xl1857473><span style='mso-spacerun:yes'> </span></td>
  <td class=xl2477473></td>
  <td colspan=2 class=xl2527473><span style='mso-spacerun:yes'> </span></td>
  <td colspan=2 class=xl1857473><span style='mso-spacerun:yes'> </span></td>
  <td class=xl2477473></td>
  <td colspan=2 class=xl2527473><span style='mso-spacerun:yes'> </span></td>
  <td colspan=2 class=xl1857473><span style='mso-spacerun:yes'> </span></td>
  <td class=xl2477473></td>
  <td colspan=2 class=xl2517473 width=74 style='width:56pt'><span
  style='mso-spacerun:yes'> </span></td>
  <td colspan=2 class=xl2637473><span style='mso-spacerun:yes'> </span></td>
  <td colspan=3 class=xl2527473><span style='mso-spacerun:yes'> </span></td>
  <td colspan=2 class=xl1857473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2507473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
 </tr>
 <?php 
      $holidays0 = $this->holidays0;
      $holidays = $this->holidays;
      if(count($holidays)>0){
          $holiday_names = explode(',', $holidays[0]['holiday_names']);
          $holiday_dates = explode(',', $holidays[0]['holiday_dates']);
     }
     if (count($holidays0)>0) {
          $holiday_names0 = explode(',', $holidays0[0]['holiday_names']);
          $holiday_dates0 = explode(',', $holidays0[0]['holiday_dates']);
     }
      $holidaycal = "";
       for ($i=0; $i < count($holiday_dates); $i++) { 
         $holidaycal .= "<tr><td class=xl2617473>".$holiday_dates[$i]."</td>&nbsp;<td>".$holiday_names[$i]."</td></tr>";
       }
       for ($i=0; $i < count($holiday_dates0); $i++) { 
         $holidaycal .= "<tr><td class=xl2617473>".$holiday_dates0[$i]."</td>&nbsp;<td>".$holiday_names0[$i]."</td></tr>";
       }
  ?>
 <tr class=xl727473 height=19 style='mso-height-source:userset;height:14.25pt'>
  <td colspan=2 height=19 class=xl2607473 style='height:14.25pt'>Total Actual
  Hours Worked</td>
  <td class=xl767473><span style='mso-spacerun:yes'> </span></td>
  <td class=xl1857473></td>
  <td class=xl1857473></td>
  <td class=xl727473></td>
  <td class=xl2517473 width=37 style='width:28pt'></td>
  <td class=xl2517473 width=37 style='width:28pt'></td>
  <td class=xl1857473></td>
  <td class=xl1857473></td>
  <td class=xl2477473></td>
  <td class=xl2527473></td>
  <td class=xl2527473></td>
  <td class=xl1857473></td>
  <td class=xl1857473></td>
  <td class=xl2477473></td>
  <td class=xl2527473></td>
  <td class=xl2527473></td>
  <td class=xl1857473></td>
  <td class=xl1857473></td>
  <td class=xl2477473></td>
  <td class=xl2527473></td>
  <td class=xl2527473></td>
  <td class=xl1857473></td>
  <td class=xl1857473></td>
  <td class=xl2477473></td>
  <td class=xl2527473></td>
  <td class=xl2527473></td>
  <td class=xl1857473></td>
  <!-- <td colspan=3 class=xl2617473><?php echo $this->empHolidaysWeekends['holiday_dates']; ?></td>
  <td class=xl2537473 colspan=7><?php echo $this->empHolidaysWeekends['holiday_names']; ?></td> -->
  <td class=xl1857473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2507473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
 </tr>
 <?php echo build_calendar_Holiday_View(); ?>
 <!-- <tr class=xl727473 height=19 style='mso-height-source:userset;height:14.25pt'>
  <td colspan=2 height=19 class=xl2607473 style='height:14.25pt'>Total LOE<span
  style='mso-spacerun:yes'>  </span>%age</td>
  <td class=xl757473><span style='mso-spacerun:yes'> </span></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl2547473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td colspan=3 class=xl2617473><?php echo $this->empHolidaysWeekends['holiday_dates']; ?></td>
  <td colspan=8 class=xl2627473><?php echo $this->empHolidaysWeekends['holiday_names']; ?></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2487473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
 </tr> -->
 <tr class=xl727473 height=15 style='mso-height-source:userset;height:11.25pt'>
  <td height=15 class=xl1857473 style='height:11.25pt'></td>
  <td class=xl1857473></td>
  <td class=xl757473></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl2547473 width=37 style='width:28pt'></td>
  <td class=xl1847473 width=37 style='width:28pt'></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td colspan=3 class=xl2617473></td>
  <td class=xl2537473></td>
  <td class=xl2537473></td>
  <td class=xl2537473></td>
  <td class=xl2537473></td>
  <td class=xl2537473></td>
  <td class=xl2537473></td>
  <td class=xl2537473></td>
  <td class=xl2537473></td>
  <td class=xl2537473></td>
  <td class=xl2537473></td>
  <td class=xl2537473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
 </tr>
 <?php echo $holidaycal; ?>
 <tr>
    <td class=xl1857473>Comment: </td>
    <td class=xl1857473><?php echo $this->status[0]['comment']; ?></td>
  </tr>
 <tr class=xl727473 height=21 style='height:15.75pt'>
  <td height=21 class=xl2557473 colspan=6 style='height:15.75pt'>I CERTIFY THAT
  ABOVE IS TRUE AND CORRECT<span style='mso-spacerun:yes'> </span></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2477473></td>
  <td class=xl2477473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2577473>&nbsp;</td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
 </tr>
 <tr class=xl727473 height=26 style='mso-height-source:userset;height:19.5pt'>
  <td colspan=18 height=26 class=xl2677473 style='height:19.5pt'><span
  style='mso-spacerun:yes'>                                                                                        
  </span>Employee</td>
  <td colspan=25 class=xl2587473><?php if($this->status[0]['status']=="Approved"){echo "Approved";} ?> <span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
 </tr>
 <tr class=xl655357473 height=32 style='mso-height-source:userset;height:24.0pt'>
  <td height=32 class=xl2567473 colspan=3 style='height:24.0pt'>Signature: <u><?php echo $this->fullName; ?></u></td>
  <td class=xl655357473></td>
  <td class=xl655357473></td>
  <td class=xl655357473></td>
  <td class=xl655357473></td>
  <td class=xl655357473></td>
  <td class=xl655357473></td>
  <td class=xl655357473></td>
  <td class=xl2567473 colspan=7>Date: <u><?php echo date( 'F d, yy', strtotime($this->status[0]['created'])); ?></u><span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td colspan=9 class=xl2587473>Signature:<u><?php if($this->status[0]['status']=="Approved"){echo $this->approver['userfullname'];} ?></u></td>
  <td class=xl2567473></td>
  <td colspan=14 class=xl2677473>Date:-<span style='mso-spacerun:yes'> 
  </span> <u><?php if($this->status[0]['status']=="Approved"){echo date( 'F d, yy', strtotime($this->status[0]['modified']));} ?> </td>
  <td class=xl655357473></td>
  <td class=xl655357473></td>
  <td class=xl655357473></td>
  <td class=xl655357473></td>
  <td class=xl655357473></td>
  <td class=xl655357473></td>
 </tr>
 <tr class=xl727473 height=26 style='mso-height-source:userset;height:20.1pt'>
  <td height=26 class=xl727473 style='height:20.1pt'></td>
  <td class=xl897473></td>
  <td class=xl897473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2577473>&nbsp;</td>
  <td class=xl2577473>&nbsp;</td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2577473>&nbsp;</td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl2567473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
  <td class=xl727473></td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=99 style='width:74pt'></td>
  <td width=73 style='width:55pt'></td>
  <td width=66 style='width:50pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=37 style='width:28pt'></td>
  <td width=39 style='width:29pt'></td>
  <td width=39 style='width:29pt'></td>
  <td width=39 style='width:29pt'></td>
  <td width=39 style='width:29pt'></td>
  <td width=39 style='width:29pt'></td>
  <td width=0></td>
  <td width=0></td>
  <td width=43 style='width:32pt'></td>
  <td width=0></td>
  <td width=0></td>
  <td width=0></td>
  <td width=0></td>
  <td width=0></td>
  <td width=64 style='width:48pt'></td>
 </tr>
 <![endif]>
</table>

</div>
</body>
</html>
    </div>
</div>
<div id="idreject_note" style="display:none">
    <span class="textarea_bg">
        <textarea id="idtxtrejectnote" class="textarea_re textarea_two_appri" maxlength="200"></textarea>
    </span>
</div>  
<script type="text/javascript" language="javascript" >
$(document).ready(function(){
$('#idhidselmn').val('<?php echo $selYrMon?>');
 var str_type = '<?php echo $type;?>';
if(str_type=='month')
{
	$("#month").addClass("dis_none");
}else
{
	$("#week").addClass("dis_none");
	$("#show_cal").css("display", "block");
}
	options = {
	    pattern: 'yyyy-mm', // Default is 'mm/yyyy' and separator char is not mandatory
	   // selectedYear: <?php echo date('Y');?>,
	    selectedYear: <?php echo (isset($selectedYrMon[0]))?$selectedYrMon[0]:date('Y');?>,
	    startYear: <?php echo $min_year;?>,
	    finalYear: <?php echo date('Y');?>,
	};
	
	$('#start_date').monthpicker(options);
	$('#start_date').monthpicker().bind('monthpicker-click-month', function (e, month) {
	    var year_month=$('#start_date').val();
	    var selmn_split=year_month.split('-');
	    var month_names=new Array('','January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December');
	    $('#start_date').val(month_names[parseFloat(selmn_split[1])]+' '+selmn_split[0])
	    $('#idhidselmn').val(year_month); 
	    var act=$( "#idempaccordion" ).accordion( "option", "active");
        if(act!==false && act>=0)
            act=act;
        else 
            act=false;
        var selmn=year_month;   
        var dobj=new Date();
        var dyear=dobj.getFullYear();
        var dmonth=dobj.getMonth();
        dmonth=parseFloat(dmonth)+1;
        if(parseFloat(dmonth)<10)
        {
            dmonth='0'+dmonth;
        }
        var dselmn=dyear+'-'+dmonth;   
        var type=$("#timesheetView").val();
        var hidweek=$('#idhidweek_ac').val();
        if(type=='month' && !($('#show_cal').is(':visible')))
        {
        	displayEmpTimesheetMonthly(selmn);
        }
        else
        {    
            if(dselmn==selmn)
                hidweek='';
            else 
                hidweek=1;
            emp_display_weeks_monthly(selmn,'<?php echo $data->id;?>',hidweek);
        }
	
	}).bind('monthpicker-change-year', function (e, year) {
	    
	    var dobj=new Date();
	    var dyear=dobj.getFullYear();
	    var dmonth=parseFloat(dobj.getMonth());
	    if(year==dyear)
	    {
	        var dis_months=new Array();
	        for(i=(dmonth+2);i<=12;i++)
	        {
	            dis_months[i]=i;
	        }
	        $('#start_date').monthpicker('disableMonths', dis_months);
	    }
	    else 
	    {
	        $('#start_date').monthpicker('disableMonths', []);
	    }
	
	});
	var dobj=new Date();
	var dmonth=parseFloat(dobj.getMonth());
	var dis_months=new Array();
	for(i=(dmonth+2);i<=12;i++)
	{
	    dis_months[i]=i;
	}
	$('#start_date').monthpicker('disableMonths', dis_months);
	var year_month='<?php echo $selYrMon;?>';
    var selmn_split=year_month.split('-');
      var month_names=new Array('','January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December');
    $('#start_date').val(month_names[parseFloat(selmn_split[1])]+' '+selmn_split[0])
    var emplistflag = $('#emplistflag').val();
	if('<?php echo $type;?>' == "month"){
		displayEmpTimesheetMonthly('<?php echo $selYrMon;?>',emplistflag);
	}else{
		emp_display_weeks_monthly('<?php echo $selYrMon;?>','<?php echo $data->id;?>','<?php echo $hidweek;?>',emplistflag);
	}
	
});
</script>
<style type="text/css">
	.calender_view_div{
		display: none;
	}
</style>